### ISSUE TITLE
Ne fonctionne pas

### ISSUE THREAD

**Issue by jojodudu** [jperon/lyluatex#10]
Bonjour,

chez moi, il semble que la compilation ne veule pas se faire pour la musique lilypond. Il me renvoie ceci, sans faire la compilation :
! LuaTeX error ./lyluatex.lua:82: attempt to index local 'p' (a nil value)
stack traceback:
	./lyluatex.lua:82: in function 'compiler_ly'
	./lyluatex.lua:66: in function 'inclure_ly'
	[\directlua]:1: in main chunk.
\keycmd->includely ...{\commandkey {staffsize}} )}

Pourriez-vous m'aider, s'il vous plaît?

**Comment by jperon** [comment]
Bonjour,

Désolé de ne vous avoir pas répondu : j'ai été, pour des raisons professionnelles, sans accès à internet pendant pratiquement un an…
Avez-vous bien pensé à exécuter `lualatex` avec le paramètre `shell-escape`, ou bien à mettre `lilypond` dans votre variable `shell_escape_commands` dans `texmf.cnf` ?

**Comment by jojodudu** [comment]
Bonjour,
Merci beaucoup pour votre réponse. J'ai réessayé, et finalement cela fonctionne. C'est formidable, j'ai passé des heures à essayer de trouver un script qui fasse ce travail, et le voilà. D'autant plus formidable que cela semble compatible avec gregorio, et là aussi j'ai passé des heures à chercher, car le but est de faire des livres de chants contenant du grégorien et de la polyphonie en même temps, tant qu'à faire, sur la même page. Et cela n'est pas si facile en LaTeX (ni avec d'autres logiciels d'ailleurs...). Mais grâce à vous c'est faisable, merci infiniment!

**Comment by jperon** [comment]
Si votre objectif est tel, peut-être serez-vous intéressé par [musite](https://github.com/musite-project/musite), qui permet avec une interface web de saisir des documents tels que [celui-ci](https://musite.dtdns.net/fr/Documentation/exemples/Magnificat.tex), sans avoir à saisir de ligne de commande.

**Comment by jojodudu** [comment]
Bonjour,
      
      Je ne voudrais pas abuser avec mes problèmes : je vous remercie
      pour musite, sauf que je n'arrive pas à le faire fonctionner. J'ai
      installé le Docker, python, matplotlib, téléchargé musite, mais
      impossible de faire fonctionner musite, c'est-à-dire que j'ai
      d'abord un message d'erreur dans Kitematic que je vous mets en bas
      de ce message, puis si je met par exemple http://localhost:5000
      comme j'ai configuré le port, je me retrouve sur
      "www.loaclhost.com:5000" avec une page d'erreur.
      Je suis avec Windows 10, et derrière un proxy correctement
      configuré (normalement... ; les adresses locales ne sont pas
      prises en compte, et ngix par exemple fonctionne très bien)
      
      Pourriez-vous m'aider à résoudre ce problème, s'il vous plaît? Je
      n'ai pas trouvé de documentation sur internet malgré mes
      recherches, et mon Anglais est plutôt très limité...
      Merci par avance,
      Cordialement,
      
      Jordan
-------------------------------------------------------------------------
    
    /usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
      
      ----------------------------------------------------------
    
    
    Le 25/08/2016 à 18:00, jperon a écrit :
    
    
      Si votre objectif est tel, peut-être serez-vous intéressé par musite,
        qui permet avec une interface web de saisir des documents tels
        que celui-ci,
        sans avoir à saisir de ligne de commande.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jperon/lyluatex","title":"jperon/lyluatex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jperon/lyluatex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jperon in #10: Si votre objectif est tel, peut-être serez-vous intéressé par [musite](https://github.com/musite-project/musite), qui permet avec une interface web de saisir des documents tels que [celui-ci](https://musite.dtdns.net/fr/Documentation/exemples/Magnificat.tex), sans avoir à saisir de ligne de commande."}],"action":{"name":"View Issue","url":"https://github.com/jperon/lyluatex/issues/10#issuecomment-242441807"}}}

**Comment by jperon** [comment]
Vous ne m’embêtez pas du tout ! En revanche, il sera peut-être plus commode
de continuer cette conversation directement à mon adresse de courriel :
cataclop@hotmail.com

Pour ce qui est du message “d’erreur”, ce n’est pas une erreur, et c’est
plutôt bon signe… La seule chose, à mon avis, vient de ce que l’adresse à
saisir n’est pas *localhost*. Il faut bien voir que Kitematic fait tourner
une machine virtuelle avec VirtualBox, laquelle contient docker avec
l’image musite. Il faut donc saisir à la place de *localhost* l’adresse IP
de la machine virtuelle ; je n’ai pas de machine Windows sous la main, mais
d’après ce qu’indiquerait une rapide recherche sur google, peut-être que
ceci pourrait fonctionner : http://192.168.99.100:5000

Bon courage !
​
