### ISSUE TITLE
Pdf optimization

### ISSUE THREAD

**Issue by jperon** [jperon/lyluatex#113]
Actually, it's possible with `optimize-pdf` #75 to shrink the size of each included pdf. Starting with LilyPond 2.19, it's possible to use the option `-O TeX` (or better, `-O TeX-GS`, but needs to call `gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=FINAL.PDF FILE.PDF` after compilation). It should be implemented, with tests to ensure that the LilyPond `program` allows it.

**Comment by uliska** [comment]
I'm not fully aware of the implications, but there is a general issue with the `gs` version being compatible with the used LilyPond version. When invoking the lilypond executable directly the system-default version of GhostScript will be used, which may or may not work together.
The regular (downloaded) LilyPond installation has a wrapper script for LilyPond that sets `LD_LIBRARY_PATH` (?) to a directory inside the LilyPond installation. This directory actually only contains another directory whose name specifies the GhostScript version to be used.

I think that when we are going to invoke GhostScript directly we should at least keep that issue in mind.

**Comment by jperon** [comment]
Fixed in b62c51e02c3944b33d737696edd285ddb776c1f1.
