### ISSUE TITLE
lilypond-book compatibility

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#115]
This basically is a place-holder issue for the [lilypond-book project](https://github.com/jperon/lyluatex/projects/1).

I don't want to duplicate that project as a check box list here, but it's a way to keep a reference in the [Release v1](https://github.com/jperon/lyluatex/milestone/1) milestone

**Comment by jperon** [comment]
I think this one could be considered as done. Would someone have big enough sources to check it ?
The only real caveat I've got in mind is that `\begin{lilypond}` has to be written `\begin{lilypond}[]`.

**Comment by uliska** [comment]
I suggest you write to the lilypond-user list and ask people to check it out and test existing real-world files.

Regarding the empty options issue I suggest to provide a script that automatically inserts empty options if necessary. At first I thought this was strange but actually this could even be implemented as a command in `lyluatex`, so compiling a file with

```TeX
\usepackage{lyluatex}
\begin{document}
\convertlytex{path/to/lilypond-book-file}
\end{document}
```
would parse and update that file. It could also be given a directory and an extension to batch-process them.

**Comment by uliska** [comment]
So we agree that this is fully completed, but we should ask specifically for this point when asking for testing.

**Comment by jperon** [comment]
Just pushed a note about that in the doc, but otherwise OK.

**Comment by uliska** [comment]
@jperon I think we can close this issue now. From *our* side compatibility is provided, and I think that instead of keeping this issue open we can just wait if others report new issues.
