### ISSUE TITLE
First line/element in lilypond environment is somehow chopped

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#122]
The following `lilypond` environment fails to compile:

```lilypond
\begin{lilypond}
music = \relative {
  c d e
}
\score {
  \new Staff \music
}
\end{lilypond}
```
==> 

```
! Undefined control sequence.
l.13   music = \relative
                       { c' d e }
?
```

However, if I insert a line at the beginning, it works:

```lilypond
\begin{lilypond}

music = \relative {
  c d e
}
\score {
  \new Staff \music
}
\end{lilypond}
```

`\lilypond` and `lilypondfile` are not affected, so it must be related to the way the body of the environment is passed to Lua or how Lua processes that content

**Comment by jperon** [comment]
I had seen that while testing, and didn't find a solution to use `ly` without options. A workaround is to put an empty `[]`:

```lilypond
\begin{lilypond}[]
music = \relative {
  c d e
}
\score {
  \new Staff \music
}
\end{lilypond}
```

In the same way, if you want to wrap `ly` without any option in another environment, you have to use `\ly[]`.

I fear we'll have to close this as a *wontfix* and document it.
