### ISSUE TITLE
Check fragment option

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#127]
There's something fishy with fragments.

```lilypond
\begin{lilypond}[]
\paper { page-count = 2 }
  { \repeat unfold 256 c' }
\end{lilypond}
```
fails (in LilyPond), and the generated `ly` shows that there's a wrapped `{}` *around* the `\paper {}`.

So obviously the environment is wrapped like the `\lilypond` command.
Earlier I had also noticed false warnings about fullpage and relative or fragment, which I intended to look into even before noticing this compilation failure.

I will look into that, but if you should be ready to do it earlier than me, @jperon, then simply assign yourself, as I will do when I have the time to actually work on this.

**Comment by jperon** [comment]
Fixed in #126. This comes from the fact we have `fragment` as a default; but we also have a condition that deactivates it when there is something incompatible. I knew that `\score` was incompatible with it, I didn't know it for `\paper`.

**Comment by uliska** [comment]
ok, what about \layout?

Basically anything that can be entered on top-level?

Am 12. Februar 2018 12:14:57 MEZ schrieb jperon <notifications@github.com>:
>Fixed in #126. This comes from the fact we have `fragment` as a
>default; but we also have a condition that deactivates it when there is
>something incompatible. I knew that `\score` was incompatible with it,
>I didn't know it for `\paper`.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jperon** [comment]
I've just added some more. Please review it and tell me whether I forgot some.

**Comment by uliska** [comment]
Actually this is very much incomplete, and I think there's no hope fixing this by adding exceptions. There are so many things that can go outside at top-level. Try for example

```TeX
\begin{lilypond}[]
\markup "Some top-level markup"
{
  c'
}
\end{lilypond}
```

or place `#(define a-varlable #t)` there, or `\book`. Or a variable definition `pattern = { a' b' a' c'' }`.

The "proper" approach would be to wrap the content in braces exactly when the first item is a LilyPond pitch. But again, this isn't trivial as this depends on the language (OK, we do know that, but still that would require us to define regexes for all possible pitches in all possible languages.

Maybe the most sensible solution would actually be to always assume `nofragment` in the `lilypond` environment and in `\lilypondfile` but `fragment` in `\lilypond`. If I'm not mistaken lilypond-book does *never* assume `fragment` without an explicit option.

**Comment by jperon** [comment]
Added a fix in  4355162: when a command is encountered at the beginning of the score, `fragment` is deactivated.
I know it won't cover all cases (for example when the first element is a variable that gets declared), but I'd really like to avoid making `fragment` the default option:
- to avoid added complexity in the code (distinguishing between command and environment);
- to discourage as much as possible the use of inline scores when the score gets bigger.

I know this isn't the behaviour of `lilypond-book`, but I think that it's better to have "short typing for short fragments":
```tex
\begin{lilypond}[]
a b c
d e f
\end{lilypond}
```

and "long typing for long fragments":
```tex
\begin{lilypond}[nofragment]
MY_LONG_SCORE_WITH_VARIABLES_AND_SO_ON
WHOSE_PLACE_WOULD_BE_IN_SEPARATE_FILE
\end{lilypond}
```

The auto-detection as it is now will detect enough cases to let the user explicitly state `nofragment` in corner cases.

**Comment by uliska** [comment]
But it will also detect false positives when the given *music expression* starts with a command

```TeX
\begin{lilypond}[]
\clef bass
c1
\end{lilypond}
```

I think the only thing we can do for now is to document this as carefully as possible.

**Comment by jperon** [comment]
OK, so I reverted  4355162: I think it's easier to state that `fragment` is the default behavior, and that if auto-detection fails, one just has to add `nofragment`.
