### ISSUE TITLE
print-page-number and fullpagealign=staffline don't go well together

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#132]
When `print-page-number` is set and `fullpagealign` is not set to `crop` (but to the default `staffline`) then the page number is printed directly at the top of the paper.

I don't think there's much to be done about it, and this should be documented instead.

Related to #56

**Comment by jperon** [comment]
With dc316947143db20b21e7ac16c37711ac6760a878, and as it would be really weird to use those options together, I do think that documenting it and closing as a *wontfix* is the good way to go.
