### ISSUE TITLE
Carefully document the auto-wrapping behaviour

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#134]
#127 hasn't been resolved in a completely satisfactory manner, there will be numerous cases where the heuristics will fail to detect fragment/nofragment status of the `lilypond` environment's contents.

It has to be carefully explained what the underlying considerations are, how the algorithm works and what the user should do in case of problems.

**Comment by jperon** [comment]
With 4355162 reverted, I think it's easier to state that `fragment` is the default behavior, and that if auto-detection fails, one just has to add `nofragment`.

**Comment by jperon** [comment]
Solved as of 01104c28d198fbbf07ed71cf8d0518c9063c67f1
