### ISSUE TITLE
Review behaviour with automatic inline rendering

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#136]
I'm not fully clear anymore how we wanted `\lilypond` to behave when the insertion mode is not explicitly set.

**Comment by jperon** [comment]
Aren't the comments of #45 satisfactory ? I think `insert=inline` is a good default for `\lilypond`, as it shouldn't be used for anything but very short fragments.

**Comment by uliska** [comment]
yes, they are, and this issue should be closed now.

Am 17. Februar 2018 17:46:28 MEZ schrieb jperon <notifications@github.com>:
>Aren't the comments of #45 satisfactory ? I think `insert=inline` is a
>good default for `\lilypond`, as it shouldn't be used for anything but
>very short fragments.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jperon/lyluatex/issues/136#issuecomment-366453974

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
handled in #137
