### ISSUE TITLE
Path to release

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#143]
I think we are nearly at the point of preparing a release (supposing there will be no major issues with #142).

How are we going to proceed? My suggestion is a three-step path (after merging of that PR):

* Ask people to test from Github, with particular focus also on the manual (that it is understandable, complete and consistent with the actual behaviour).  
This can be requested on mailing lists, and I'd suggest to ask some people personally
* When that is complete make a "1.0 beta" release on CTAN
* After some time make a 1.0 release on CTAN

**Comment by jperon** [comment]
OK for me, but after merging #142, I'd like to make some optimizations I had in mind, but I delayed to avoid merge conflicts.

**Comment by uliska** [comment]
Mailing lists to be notified:

* [ ] lilypond-user
* [ ] tex-music
* [ ] tex-live
* [ ] MEI (only for release info)
* [ ] Tex-D-L (no idea, was a friend's suggestion)
* [ ] DANTE
* [ ] texhax

Please add to the list and "register" before writing a post to a list.

**Comment by jperon** [comment]
@uliska Would you mind making the notifications ? I'm very busy at work ATM, so it will be quite complicated for me.

**Comment by uliska** [comment]
Ok, I'll do so for the lists I'm subscribed to and ask (or rather allow) the friend to forward to the remaining two.

**Comment by uliska** [comment]
https://github.com/jperon/lyluatex/issues/177 (as a link to be included in mailing list posts)

**Comment by uliska** [comment]
We didn't receive any confirmations but also no objections. So I think we could now prepare the upload to CTAN. I think #168 can be investigated between the beta and the final release, we should just fix the "issue" with straight quotes in the manual (as commented in #177).

What do you think, @jperon ?
Does the Makefil have to be updated for this? Would you do that?

**Comment by jperon** [comment]
That's now ready in #179.
