### ISSUE TITLE
Should \lilypondfile try to wrap a music expression?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#149]
Obviously `\lilypondfile` does try to wrap the content in a music expression (as shown by the warning).

I think that included files will usually be expected to contain complex material and not require wrapping in a music expression.

Should this behaviour be switched off and `\lilypondfile` *not* be wrapped?

**Comment by jperon** [comment]
I'm going to look at this, and to make some code optimizations. If you plan to make other changes, please tell me, because the changes I'm going to make could likely cause merge conflicts in that case.

**Comment by uliska** [comment]
No, I won't do so, just go through the manual.

There's one thing I noticed and that you could do when you're polishing the code: currently unknown options are only caught as package options but are silently ignored as local options or with `\lysetoption`. This can cause hard-to-track issues for misspelled options. Should I create a separate issue for that?
