### ISSUE TITLE
Link to appended examples doesn't work

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#167]
In https://github.com/jperon/lyluatex/commit/b4fd634d01635f3cb287a331e911c3d06225e7d6 I've set up a linking system to the example documents appended to the manual (following the `pdfpages` manual). But while the links *are* actually created they don't point to the correct page but rather the very end of the manual.

@jperon any ideas?

**Comment by jperon** [comment]
Just pushed a fix.

**Comment by uliska** [comment]
Thanks, but while I understand the code the link still points to the last page of the manual.

**Comment by uliska** [comment]
Oh, sorry. I had obviously removed something erroneously. This was only partially related (see 37e24bbcf64d038a61d4cf1a6d20f75c0b75e86e), but now it seems to work.
