### ISSUE TITLE
Where will the `examples` directory end up in  TeX distributions

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#168]
How can we know or influence where the `examples` directory will end up in distributions such as `TeXLive`?

This is relevant for
* building the manual (which I think distributions want to do themselves)
* pointing users to them from the manual

If noone already knows I suggest to post to the tex-live user list.

**Comment by jperon** [comment]
I guess it will end in `texmf/doc/support/lyluatex/`, but I'm not sure at all.

**Comment by rpspringuel** [comment]
I'm fairly certain that it has to do with the CTAN upload location.  However, if you include a tds.zip file in that upload then it will be fairly easy for the TeXLive people to match whatever structure is there.

**Comment by jperon** [comment]
That said, I think we could avoid having to include that directory by organizing things otherwise. I've an idea about this, but I'll have to work on it tomorrow.

**Comment by uliska** [comment]
Am 1. März 2018 19:46:05 MEZ schrieb "Br. Samuel Springuel" <notifications@github.com>:
>I'm fairly certain that it has to do with the CTAN upload location. 
>However, if you include a tds.zip file in that upload then it will be
>fairly easy for the TeXLive people to match whatever structure is
>there.

Actually they encourage *not* to provide a tds.zip file if you're not 100% familiar with it.
They are ready to take suggestions and discuss the best way with us (that was my experience with lilyglyphs where it also was nonstandard).

The requirements for CTAN are different than the live etc. in CTAN it can simply be a mirror of the development repository.

However, we should know that before uploading to CTAN so we can add a comment in the manual.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
My take on this would be to put both the `lyluatex.md`, the `.cls` files and the example files in one subdirectory `documentation`. That way we can reference the included example files with a relative link without path.
I'll write a post on the tex-live list, and I'm confident we'll have more reliable information by tomorrow.

**Comment by uliska** [comment]
I think we can leave this open and simply release a beta version to CTAN. When that hits TeXLive we can inspect the resulting package and update the manual (introduction to "Examples") before releasing v1.

**Comment by uliska** [comment]
This has been resolved by a) integrating the examples in the manual and b) referencing the `examples` folder in the Github repository
