### ISSUE TITLE
Pre-beta-1.0 testing required

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#177]
After intense development (ca. 560 out of 625 changesets have been committed since Jan 15) we are targeting a `v1.0` release. The main objective of this version is full compatibility with [lilypond-book](http://lilypond.org/doc/v2.19/Documentation/usage/lilypond_002dbook.en.html) documents, but it includes much more.

Attached to this issue is [lyluatex.pdf](https://github.com/jperon/lyluatex/files/1789583/lyluatex.pdf), the manual compiled from commit 053f3c6fe48141b6a70b5870b62caf8fc119e2a8, the current state of the repository.

We ask for review and testing before we will release a `v1.0b` version to CTAN. When testing the package please keep the following questions in mind:

* Is the manual comprehensive?
* Is the manual correct, i.e. does it properly match the behaviour of the package?
* Is the order of information in the manual useful, is it confusing?
* Are there any glitches in the resulting output?
* Do you manage to make the package fail (e.g. produce grossly wrong results, crash)
* Any real bugs?
* Should the package have additional features if so we'd specifically need to hear about stuff that should be added immediately, before a v1 release

If you have any comments or observations to report please open issues on this tracker rather than discussing them on mailing lists that linked to this call for review.

**Comment by lemzwerg** [comment]
Nice!

BTW, you should check the example sections in the manual: They are using the wrong single quote and double quote characters (i.e., curved ones instead of straight ones, cf. page 4).

**Comment by uliska** [comment]
> (i.e., curved ones instead of straight ones, cf. page 4).

No, that's the Inconsolata font, 
![image](https://user-images.githubusercontent.com/1812148/37103897-9e9904aa-222b-11e8-855b-ec60896d2275.png) vs. 
![image](https://user-images.githubusercontent.com/1812148/37103924-b0123ac6-222b-11e8-8e4a-f4a94a686539.png)

**Comment by lemzwerg** [comment]
OK.  Assuming that you are using 'InconsolataN' (which is part of TeXLive) I strongly suggest that you activate OpenType feature 'ss01' so that real straight quotes are used.

**Comment by uliska** [comment]
@lemzwerg  I'm sorry, but how do I do that with `fontspec`? From the manual I thought `StylisticSet=1` or `StylisticSet=01` would be the way to go but both don't make a difference.

**Comment by lemzwerg** [comment]
I explicitly wrote 'InconsolataN', not 'Inconsolata' – the latter doesn't contain straight quotes. Saying
```
\setmonofont[Scale=MatchLowercase, StylisticSet=1]{InconsolataN}
```
works for me.

**Comment by uliska** [comment]
Hm, I was sure I had tried all combinations. However, with the last commit it *does* change the quotes in the manual.

@jperon I think we can close this issue since we didn't receive any objections.

**Comment by PunctatorFortunatus** [comment]
I'm reading the manual, and I don't think I understand how `\betweenLilypondSystems` works. I says there that with more programing it is possible to add specific instructions between specific systems, but neither the definition of the command, nor the example in the appendix clarifies this. Thank you all guys for your hard work, you are my favorite people.

**Comment by jperon** [comment]
Thank you for the report. `\betweenLilyPondSystems` is documented in [LilyPond documentation](http://lilypond.org/doc/v2.18/Documentation/usage/latex); I've added the reference in the manual. If you don't define it, it hasn't any default content (`\ifx\betweenLilyPondSystems\undefined` would return true); it may contain anything you like, so feel free to experiment !

**Comment by uliska** [comment]
I'll update the example to be slightly more expressive.
But actually this is something that doesn't have to be explained in depth by lyluatex.

**Comment by PunctatorFortunatus** [comment]
Ok, then why not just cross the reference with lilypond manual?

**Comment by fedelibre** [comment]
It took me some time to install lyluatex, since I don't have tlmgr on Fedora and I had to learn where to place the files following the [TeX Directory Structure](https://tug.org/tds/tds.html). Eventually I came up with this:

```
$ tree ~/texmf/
/home/fede/texmf/
├── scripts
│   └── lyluatex
│       └── lyluatex.lua
└── tex
    └── latex
        └── lyluatex.sty

4 directories, 2 files

```
Second, I would add a note about installing TexLive dependencies listed in `lyluatex.sty`. I had to install also `texlive-ctablestack` while I was trying to compile a test file.

Now I can compile an example using `lualatex --shell-escape luatest.tex`, **but** every time a lilypond snippet is found the ? prompt appears and I have to hit enter to go to the next step. After some Enter(s) I got the PDF file. How can I avoid this?

Thanks for the package, it looks very promising!
BTW, I guess it cannot work around [this bug](https://sourceforge.net/p/testlilyissues/issues/2968/), right?

**Comment by uliska** [comment]
> It took me some time to install lyluatex, since I don't have tlmgr on Fedora

OK, some comments to this:
* `tlmgr` is only available (IISC) when you install TeXLive from their downloads. When installing from the OS packages you don't use `tlmgr` but the OS package manager. Probably this has to be verified and clarified in the manual.
* *Currently* installing from TeXLive doesn't work because everything we've developed recently isn't there yet. So for testing you have to use the version from the Github repository.

> Eventually I came up with this:

For installing from the Github repo you can simply clone the repository anywhere and then link to that location in `~/texmf/tex/latex`. This also should be clarified in the manual.

> Now I can compile an example using lualatex --shell-escape luatest.tex, but every time a lilypond snippet is found the ? prompt appears and I have to hit enter to go to the next step. After some Enter(s) I got the PDF file. How can I avoid this?

Do you get any scores in the final PDF? What is printed *before* the ?

> BTW, I guess it cannot work around this bug, right?
I don't think so because the cropping is simply achieved by using `lilypond-book-preamble.ly`, so in that case you'll have to work around the issue in the usual way (by adding content or manually extending the `Y-extent` of something.

**Comment by fedelibre** [comment]
> For installing from the Github repo you can simply clone the repository anywhere and then link to that location in ~/texmf/tex/latex. This also should be clarified in the manual.
> 

Ok, this is easier to maintain. I've just made a symlink to the cloned repository, but then lualatex is not recognized:

```
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))[\directlua]:1:
 module 'lyluatex.lua' not found:
	no field package.preload['lyluatex.lua']
	[kpse lua searcher] file not found: 'lyluatex.lua'
	[kpse C searcher] file not found: 'lyluatex.lua'
	no file '/usr/local/lib/lua/5.2/lyluatex.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './lyluatex.so'
stack traceback:
	[C]: in function 'require'
	[\directlua]:1: in main chunk.
l.94 }
    
?
```

What's my error?

```
$ ls -l ~/texmf/tex/latex/
totale 0
lrwxrwxrwx 1 fede fede 24 11 mar 15.05 lyluatex -> /home/fede/src/lyluatex/

$ cd ~/texmf/tex/latex/lyluatex/
[lyluatex (master=)]$ pwd
/home/fede/texmf/tex/latex/lyluatex
[lyluatex (master=)]$ ls
examples  lyluatexbase.cls    lyluatex.md   manual.sh     test-alignment.tex  xml
LICENSE   lyluatex.lua        lyluatex.sty  README.en.md  test.en.tex
ly        lyluatexmanual.cls  Makefile      README.md     test.tex
```

**Comment by fedelibre** [comment]
>     Now I can compile an example using lualatex --shell-escape luatest.tex, but every time a lilypond snippet is found the ? prompt appears and I have to hit enter to go to the next step. After some Enter(s) I got the PDF file. How can I avoid this?
> 
> Do you get any scores in the final PDF? What is printed before the ?

Yes, I get the scores.

Find attached the terminal output.
[lyluatest-terminal.log](https://github.com/jperon/lyluatex/files/1800426/lyluatest-terminal.log)

**Comment by jperon** [comment]
Did you symlink both lyluatex.sty and lyluatex.lua, and did you launch mktexlsr (or texhash) after that ?

**Comment by uliska** [comment]
Am 11. März 2018 15:30:47 MEZ schrieb jperon <notifications@github.com>:
>Did you symlink both lyluatex.sty and lyluatex.lua, and did you launch
>mktexlsr (or texhash) after that ?

It's not necessary to link individual files. I'm not sure about the others, though.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fedelibre** [comment]
> Did you symlink both lyluatex.sty and lyluatex.lua, and did you launch mktexlsr (or texhash) after that ?

I symlinked only the directory. And running mktexlsr after that did not help.

At least on my system, it is necessary to link individual files and there's no need to run mktexlsr.
The following configuration is working correctly:

```
[~]$ LYLUATEX_SRC=/home/fede/src/lyluatex
[~]$ 
[~]$ echo $LYLUATEX_SRC
/home/fede/src/lyluatex
[~]$ 
[~]$ ln -s $LYLUATEX_SRC/lyluatex.sty ~/texmf/tex/latex/
[~]$ 
[~]$ ln -s $LYLUATEX_SRC/lyluatex.lua ~/texmf/scripts/
[~]$ 
[~]$ tree texmf
texmf
├── scripts
│   └── lyluatex.lua -> /home/fede/src/lyluatex/lyluatex.lua
└── tex
    └── latex
        └── lyluatex.sty -> /home/fede/src/lyluatex/lyluatex.sty

```

**Comment by jperon** [comment]
@uliska, if you don't have any objection, I think I'm going to upload to CTAN.

**Comment by uliska** [comment]
No, please go ahead. And don't be too modest with the "announcement text" ;-)
