### ISSUE TITLE
compilation failure of manual with pandoc 1.19.2.1

### ISSUE THREAD

**Issue by lemzwerg** [jperon/lyluatex#182]
[git 89c021b86]

Saying `make manual` doesn't work with pandoc 1.19.2.1 if combined with the forthcoming TeXLive 2018 (i.e., TeXLive SVN revision 47442).

The compilation stops with
```
! LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.26 \hypersetup
              {
? H
The package hyperref has already been loaded with options:
  [colorlinks=true]
There has now been an attempt to load it with options
  [unicode=true]
Adding the global options:
  colorlinks=true,unicode=true
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
? 
```

**Comment by jperon** [comment]
@lemzwerg Is this issue still relevant for you ?

I think this would be a `Pandoc` bug rather than `lyluatex`. If no one has any objection, I'll close this issue.

**Comment by fedelibre** [comment]
FWIW I can run `make manual` successfully on current master using Pandoc version 2.1.2 and TexLive 2018.

```
$ tex --version
TeX 3.14159265 (TeX Live 2018)
```

**Comment by lemzwerg** [comment]
My report was a bit sloppy, sorry for that.  What I actually wanted to say is that `make manual` should emit a warning against invalid combinations of pandoc and TeXLive versions, or at least describe somewhere in the documentation which version(s) of pandoc and TeXLive are known to work.

**Comment by jperon** [comment]
Last commit adds a warning when `make manual` is called with pandoc < 2.
