### ISSUE TITLE
"fragment=false, ragged-right=true" can fail

### ISSUE THREAD

**Issue by lemzwerg** [jperon/lyluatex#184]
[lyluatex 2018/03/12 v1.0b]

Consider the following MWE.
```latex
\documentclass{article}

\usepackage[fragment=false,
            ragged-right=true]{lyluatex}

\begin{document}

\begin{lilypond}
  \new Voice { f1 \break f1 }
\end{lilypond}

\end{document}
```
which produces
![bug-raggedright](https://user-images.githubusercontent.com/1630245/38610662-cf70a152-3d81-11e8-96c1-cf132d98054a.png)

This is clearly a bug.  Option `ragged-right=true` should be applied even if `fragment=false` is set.

**Comment by jperon** [comment]
Fixed in last developments.
