### ISSUE TITLE
failure if blank lines in \lilypond

### ISSUE THREAD

**Issue by lemzwerg** [jperon/lyluatex#186]
[lyluatex 2018/03/12 v1.0b]

The definition of the `\lilypond` macro is too fragile.  This MWE containing a blank line
```latex
\documentclass{article}
\usepackage{lyluatex}

\begin{document}
\lilypond{
  f1

  f1
}
\end{document}
```
causes the following error
```
Runaway argument?
{ f1 
! Paragraph ended before \\lily was complete.
<to be read again>
\par
l.7
   
? x
```

You probably should check how [`\newcommand`](https://tex.stackexchange.com/questions/209678/problem-with-defined-macro-and-blank-lines) solves this issue.

**Comment by jperon** [comment]
The problem comes from the way we have to pass lilypond code to lua with a macro, `\luatexluaescapestring`. That's why `\lily` is only intended to type very small extracts: as soon as your score is long enough, you should use the environment.

**Comment by lemzwerg** [comment]
Hmm.  It's not clear to me how my MWE could be ever considered as 'long'...

If you don't want to handle empty lines in `\lilypond` this should be documented IMHO.

**Comment by jperon** [comment]
Sorry, in fact the cause wasn't what I thought. Fix coming.
