### ISSUE TITLE
lilypond environment should work with 'insert=inline' also

### ISSUE THREAD

**Issue by lemzwerg** [jperon/lyluatex#188]
[lyluatex 2018/03/12 v1.0b]

This issue contains a wishlist item and a bug report :-)

The following MWE
```latex
\documentclass{article}
\usepackage{lyluatex}

\begin{document}
foo
\begin[inline=indent]{lilypond}
  f1
\end{lilypond}
bar
\end{document}
```
shows how I would like to use the lilypond environment; the code should be completely equivalent to `\lilypond[inline=indent]{...}`.

However, it doesn't work.  Right now, there is a bug in `lyluatex.lua`, making it abort instead of producing a warning:
```
...up/TeXLive/Master/texmf-dist/tex/latex/base/ltluatex.lua:109:    
Module luatexbase Error: No callback list for `process_input_buffer'
(luatexbase)             on input line 1

stack traceback:
        [C]: in function 'error'
        ...up/TeXLive/Master/texmf-dist/tex/latex/base/ltluatex.lua:109: in function 'm
odule_error'
        ...up/TeXLive/Master/texmf-dist/tex/latex/base/ltluatex.lua:116: in function 'l
uatexbase_error'
        ...up/TeXLive/Master/texmf-dist/tex/latex/base/ltluatex.lua:456: in function 'r
emove_from_callback'
        .../TeXLive/Master/texmf-dist/scripts/lyluatex/lyluatex.lua:1222: in function '
buffenv_end'
        [\directlua]:1: in main chunk.
\lyscoreend ->\directlua {ly.buffenv_end()}
                  
l.8 \end{lilypond}
   
? x
```

**Comment by jperon** [comment]
I guess that:

1. you mean `insert=inline`, as `inline=indent` doesn't mean anything (at least for `lyluatex`);
2. you mean `\begin{lilypond}[insert=inline]`, not `\begin[insert=inline]{lilypond}` (in environments, optional parameters are after the environment's name).

The second point should avoid the error message with stack traceback.

For the first part, it isn't possible to have the `lilypond` environment behave exactly as the macro, as it is an environment. If you want to do that, you'll have to wrap it inside a `minipage`:

```latex
\documentclass{scrartcl}
\usepackage{lyluatex}
\usepackage{pbox}
\begin{document}
a \lilypond[insert=inline]{f1} b

a
\begin{minipage}{5em}
\begin{lilypond}
f1
\end{lilypond}    
\end{minipage}
b

\end{document}
```

Perhaps it could be implemented somehow, but I'd have to think about it, which need more time than I have now. I'll let it open for now.

**Comment by lemzwerg** [comment]
How embarassing :-)

I suggest to close this issue; a solution using either the `pbox` or `varwidth` package is good enough for me, thanks.  It might be worth to mention this solution in the manual, though.

**Comment by jperon** [comment]
@lemzwerg Could you please test with branch Fix-188 ? This should have the following MWE work:

```tex
\documentclass{article}
\usepackage{lyluatex}

\begin{document}
foo
\begin{lilypond}[insert=inline]
  f1
\end{lilypond}
bar
\end{document}
```
