### ISSUE TITLE
Add command to change LilyPond executable

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#19]
AFAICS it's currently only possible to specify a LilyPond executable through the package option. (A function `ly_definir_programme` would change that but there is no LaTeX interface available for it.

If that's correct I suggest to add a command, say `\lilypondCmd` that takes effect from the macro onwards and add an option to the LilyPond commands/environments to override the executable for a single score. 

This is usually not relevant when writing about *music* but important when writing about *LilyPond*.

**Comment by jperon** [comment]
Please feel free to test and comment.
