### ISSUE TITLE
"Crash" with large (high/long) scores

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#192]
I got an issue with a large score I wanted to compile with lyluatex and that "crashed" with the following error:

```
lyluatex.lua:126: Dimension too large
stack traceback:
	[C]: in function 'sp'
	...e/uliska/texmf/tex/latex/latex-git/lyluatex/lyluatex.lua:126: in function '
convert_unit'
	...e/uliska/texmf/tex/latex/latex-git/lyluatex/lyluatex.lua:325: in function '
parse'
	...e/uliska/texmf/tex/latex/latex-git/lyluatex/lyluatex.lua:287: in function '
bbox_func'
	...e/uliska/texmf/tex/latex/latex-git/lyluatex/lyluatex.lua:758: in function '
check_protrusion'
	...e/uliska/texmf/tex/latex/latex-git/lyluatex/lyluatex.lua:1110: in function 
'process'
	[\directlua]:1: in main chunk.
\ly@compilescore ...directlua {ly.score:process()}
```

Some `print()` debugging revealed the following values in the bounding box:

```
x_1    -35.19
x_2    435.929329
y_1    -21694.802
y_2    -0.57266199999867
```
which led me to have a look at the generated PDF (actually the score had been processed but not included in the document). And I realized that in the (unindexed) PDF the whole score is printed on *one* page, resulting in a file with dimensions 165x3017mm, which makes me think that the `y_1` value exceeds some TeX limits.

What should we do about this? Without digging into the code again (yet) I have the impression that we will never need to actually have this value, the total height of all systems glued together. Well, do we actuallly need the *height* at all in any place?
I see two possibilities:
a) don't use the unindexed pdf but the file `-1.pdf` (I think this code is only run if we already know there *is* a system)
b) don't read the *height* values at all.

What do you think, @jperon?

**Comment by jperon** [comment]
@uliska Could you please add a MWE, or an archive with an example ?

**Comment by jperon** [comment]
So here is a MWE:

```latex
\documentclass{article}
\usepackage{lyluatex}
\begin{document}

\begin{lilypond}[line-width=30mm]
{\repeat unfold 1000 { c' d' e' d' }}
\end{lilypond}

\end{document}
```

**Comment by jperon** [comment]
@uliska PR #220 is based on solution b) ; I kept the old code in commentaries, so that we can elaborate on it if we need height later. Could you please have a glance at this ?
