### ISSUE TITLE
single % comment in included lilypond file breaks compilation

### ISSUE THREAD

**Issue by fedelibre** [jperon/lyluatex#197]
If a included file contains a comment, lyluatex stops with this error:

```
(/home/fede/.local/texlive/2017/texmf-dist/tex/latex/graphics/lscape.sty))(load
 luc: /home/fede/.local/texlive/2017/texmf-var/luatex-cache/generic/fonts/otl/l
msans10-regular.luc)(load luc: /home/fede/.local/texlive/2017/texmf-var/luatex-
cache/generic/fonts/otl/lmmono10-regular.luc)...al/texlive/2017/texmf-dist/scri
pts/lyluatex/lyluatex.lua:841: invalid use of '%' in replacement string
stack traceback:
	[C]: in function 'gsub'
	...al/texlive/2017/texmf-dist/scripts/lyluatex/lyluatex.lua:841: in function '
flatten_content'
	...al/texlive/2017/texmf-dist/scripts/lyluatex/lyluatex.lua:1082: in function 
'output_filename'
	...al/texlive/2017/texmf-dist/scripts/lyluatex/lyluatex.lua:531: in function '
calc_properties'
	...al/texlive/2017/texmf-dist/scripts/lyluatex/lyluatex.lua:1088: in function 
'process'
	[\directlua]:1: in main chunk.
\ly@compilescore ...directlua {ly.score:process()}
                                                  
l.22 \end{lilypond}
                 
? 
```

Here's the included file. Note that if I use a double comment (%%) there's no error:

```
$ cat nostringnumber.ly 
\layout {
  % Use two comment signs to avoid lyluatex error
  \context {
    \Staff
    \omit StringNumber
  }
}
```

and the tex file. Note that the comment within the lilypond environment causes no error:

```
$ cat rel.tex 
\documentclass{book}
\usepackage{lyluatex}

\begin{document}

Trying to include a LilyPond file containing a custom layout:

\begin{lilypond}[nofragment]
\include "nostringnumber.ly"
% This is a comment.
music = \relative {
  \time 2/4
  c'4\3 e\2 |
  a,2\4 \bar "|." |
}
\score {
  \new PianoStaff <<
    \new Staff { \clef "treble_8" \music }
    \new TabStaff { \clef "moderntab" \new TabVoice \music }
  >>
}
\end{lilypond}

\end{document}
```

**Comment by uliska** [comment]
@fedelibre please confirm that this works.
@jperon please confirm that I didn't miss anything with simply replacing `%` with `#` in `flatten_content()`.

**Comment by fedelibre** [comment]
I confirm it works.
Thanks

**Comment by jperon** [comment]
OK for me. Sorry for my long silence, I'm too busy right now to work on `lyluatex`, and will be till june.
@uliska Many thanks !

**Comment by andrewacashner** [comment]
I encountered the same problem, but with `%%` as well: an input file containing comments results in `invalid use of '%' in replacement string. Using TeXLive 2018 with most recent updates. The input file has several lines that begin with `%% text...` and no other comments.

**Comment by andrewacashner** [comment]
Actually the same thing happens even when there are no comment characters at all in the input file!

**Comment by uliska** [comment]
@andrewacashner if you are using `lyluatex` from the TeXLive installation you will *not* have these latest fixes. These are only available from the Git repository until the next release.

**Comment by andrewacashner** [comment]
@uliska Thanks - I realized this is actually a problem with the `includepaths` option.
