### ISSUE TITLE
Multiline LilyPond comments cause crashes

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#199]
This is related to #197, but at a different point.

```TeX
\documentclass{scrartcl}
\usepackage{lyluatex}
\begin{document}
\begin{lilypond}
{
  c' d' e'
  %{
  This is a valid multiline comment in LilyPond,
  but causes a crash in lyluatex because all comments are removed
  in the first stage of digesting input code.
  %}
}
\end{lilypond}
\end{document}
```

This file causes lyluatex to crash. The reason is that (I suppose in `ly.buffenv_begin()`) all lines with (LaTeX) comments are removed from the content before they even are properly processed.
In the case of LilyPond multiline comments this removes *only* the "multiline" lines, leaving the *content* of the comment open to pass to LilyPond.

I stumbled over this because I wanted to programmatically add some Git status in comments to the LilyPond code - to have lyluatex detect modifications it can't otherwise detect (the content in my project is *not* included through `\include`).

---

I'm sorry but this part of the package is one of those I haven't really understood, so I can't fix it myself.

**Comment by jperon** [comment]
Fixed in #206.
