### ISSUE TITLE
Option to specify Lilypond executable

### ISSUE THREAD

**Issue by rpspringuel** [jperon/lyluatex#2]
I don't know if this is possible, since Lilypond is called by the lua script, but it would be nice to have an option that that allowed me to specify the lilypond executable to be used.  I usually maintain two installations of Lilypond, the most recent stable (which is set up to be called with `lilypond` at the command line) and the most recent development version (which is called with `lilypond-dev`).  Most of the time I use the stable version, but on occasion I have call to use the development version because of some feature that has been implemented there which isn't in the stable version.  What I'd like is an option in the package file that would allow me to switch between these versions.  Ideally, it would be something like the following:

`\usepackage[location=/path/to/lilypond-dev]{lyluatex}`

The `location` option would be a keyword option whose value was the location of the lilypond executable to use.  This would be the most versatile option, allowing for non-standard executable locations which are not in `PATH` as well as supporting multiple installs.  However, it would also be more complicated because it would mean passing the string option to the lua script.

A simpler implementation would be to simply create a variants of the lua scripts which called `lilypond-dev` instead of `lilypond`.  The package option would then simply tell the package to use these scripts instead of the normal ones:

`\usepackage[develop]{lyluatex}`

**Comment by jperon** [comment]
Fixed in 71b916c ; the option isn't `location`, but `program`. For example : 

    \usepackage[program=/opt/lilypond-dev/lilypond]{lyluatex}

**Comment by rpspringuel** [comment]
Works great.  Thanks.
