### ISSUE TITLE
line-width => linewidth?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#20]
I suggest considering to change the `line-width` argument to `linewidth`

While `line-width` is the LilyPond name of the paper variable `linewidth` is more in line with LaTeX syntax/expectations and also the `staffsize` argument

**Comment by jperon** [comment]
The problem is that `lyluatex` was intended to be, as much as possible, a drop-in replacement for `lilypond-book`, which uses `line-width` and not `linewidth`.

**Comment by uliska** [comment]
Ok

**Comment by rpspringuel** [comment]
It should, however, be possible to define `linewidth` as an alias keyword for `line-width`.

**Comment by uliska** [comment]
I think it is better to have only one command, so obviously `line-width`.

**Comment by uliska** [comment]
I think it is better to have only one command, so obviously `line-width`.
