### ISSUE TITLE
Relative inlucdes

### ISSUE THREAD

**Issue by rpspringuel** [jperon/lyluatex#202]
I just tried recompiling an old project which made use of `#(ly:set-option 'relative-includes #t)` inside the LilyPond files and its unable to find the included files.  Looking through the log I see the following directory in the search path: `./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/music/hymns/`  This is an incorrect amalgamation of the directory where the tex file is located (`./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/`) and the one where the ly file is located (`./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/music/hymns/`).  Since the tex file location appears 3 other times in the list and the ly file location doesn't (which is the whole problem), I suspect that it's the ly file location that's being mangled at some point.

**Comment by rpspringuel** [comment]
Hold on, it's worse than I thought.  The leading `./` indicates that the directory I gave above is a relative directory, when the path given should be absolute.  It also appears in a number of the other entries in the list of include directories:

```
/Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/svg/:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/type1/:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/otf/:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/scm:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/ps:/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/ly:./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/./Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/music/hymns/:/Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/:/Users/ss/Documents/Abbey/DivineOffice/Focus 2018/6-Friday/3-Vespers/:
```

There's all kinds of errors in that last slog of directories.

**Comment by rpspringuel** [comment]
Here's a sample project (with slightly simpler directory structure) which shows the problem.

[Archive.zip](https://github.com/jperon/lyluatex/files/2678370/Archive.zip)

**Comment by rpspringuel** [comment]
Just checked, and got a working compilation on the provided MWE.  Still getting an error on the in-situ project.  The constructed search path is as follows:

```
/Users/ss/Documents/Abbey/DivineOffice/Focus_2019/7_Jan-Monday/1-Morning:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/svg/:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/type1/:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/fonts/otf/:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/scm:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/ps:
/Applications/LilyPond-dev.app/Contents/Resources/share/lilypond/current/ly:
../../../music/antiphons/:
/Users/ss/Documents/Abbey/DivineOffice/Focus_2019/7_Jan-Monday/1-Morning/:
/Users/ss/Documents/Abbey/DivineOffice/Focus_2019/7_Jan-Monday/1-Morning/:
```

It appears to be well-formed, albeit the redundant entries at the end remain.  The third to last entry (the directory where the ly file is located) is the one of importance as the file which cannot be found is located relative to it (it's in the `music` directory).  I'm going to have to do some more experimenting (which will have to wait for some free time) to determine more about the nature of the bug.  I'll open a new issue when I figure it out.

**Comment by jperon** [comment]
OK, should be fixed in last commit.
