### ISSUE TITLE
Change line width?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#22]
As far as I can see the line width of the scores can only be changed with the package option and the local command options, but I'm not sure I've understood the code.

If that's correct I suggest adding a command that changes the line width for subsequent scores.

**Comment by jperon** [comment]
Wouldn't `\renewcommand{\lilywidth}{NEW_WIDTH}` do the trick ?

**Comment by uliska** [comment]
Yes it does.

However, I suggest to keep that issue open for some time. Eventually I may create a pull request with a nicer command (I would prefer having a command wrap it but so far I'm not familiar enough with the use to actually suggest a name).

**Comment by jperon** [comment]
This is addressed by #42 : the command is named `\lilypondLinewidth`. Thus closing.
