### ISSUE TITLE
Syntax: \begin{lilypond} content must begin on new line

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#245]
Is it a known limitation that it is not possible to write the content of a `lilypond` environment into the same line as the ` \begin` statement?

```tex
\documentclass{article}
\usepackage{lyluatex}
\begin{document}
\begin{lilypond}{ c' d' e' f' g' }\end{lilypond}
\end{document}
```

This starts LilyPond, produces an empty score and prints the characters as-is.

**Comment by jperon** [comment]
> Is it a known limitation …

Yes, it is. I just added a note in the manual.
