### ISSUE TITLE
Updated README.md file

### ISSUE THREAD

**Issue by lemzwerg** [jperon/lyluatex#260]
Appended is an updated and revised version of file [`README.md`](https://github.com/jperon/lyluatex/files/3391708/README.md.txt).

**Comment by uliska** [comment]
Closed through 1bb88622c451ad663be8fbed50114dba6c9f543f.

Thank you for the update, I've just committed on your behalf.

For the future it would maybe be somewhat more straightforward to create Pull Requests. You can do so by simply "editing" a file in the Github web interface, and it will guide you pretty painlessly through forking, committing and opening the PR.

**Comment by lemzwerg** [comment]
Thanks.  In this very case I intentionally avoided a pull request since the diff would have made it very hard to read the new version fluently due to the many changes.
