### ISSUE TITLE
CTAN directory

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#265]
I browsed the CTAN directory to find a suitable location for `luaoptions` and `luaformatters`, which I think should be put in `macros/luatex/latex`. This is also the place where `lilyglyphs` has been placed, and I think `lyluatex` should be there as well. So I'm wondering why it has been placed in `support/lyluatex` instead. Did *you* suggest that deliberately, @jperon, or was it chosen by the CTAN people?

**Comment by jperon** [comment]
Sorry for the delay of such a simple response… I didn't choose anything: I just uploaded the package [here](https://ctan.org/upload), following instructions [here](https://ctan.org/help/upload-pkg) and [there](https://ctan.org/file/help/ctan/CTAN-upload-addendum). They asked for corrections when I had forgotten details, then included it themselves where they wanted to.

**Comment by jperon** [comment]
@uliska Tell me when `luaoptions` is uploaded; I'll upload the last to CTAN afterwards.
