### ISSUE TITLE
Remove intermediate files

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#27]
Is it intentional that the `.eps` files are still present in the output directory?

**Comment by jperon** [comment]
The idea is that the user could want to debug something in case of problems. I prefer let him clean that directory himself, as I think most users will use scripts or makefiles that can do that automatically. It isn't necessary, so I could change it without problem.

**Comment by uliska** [comment]
OK, so it *is* intentional. Then I would tend to close the issue, as I don't have a strong opinion about it. But still itan *option* would be nice-to-have.

**Comment by jperon** [comment]
Given the size of `.eps`, I eventually removed them. Perhaps I'll add an option to keep them, but only if someone asks for it, as `.pdf` should be enough for debugging.
