### ISSUE TITLE
Lilypond, Texlive 2018 -> Texlive 2020 and... nothing works anymore

### ISSUE THREAD

**Issue by Brayanokles** [jperon/lyluatex#277]
I have installed Texlive 2020. But alas, my old files cannot be displayed anymore. 
What have I done wrong? I am using lilypond, but for now, it's not possible to make new files. Please help!

Here is a source:

\documentclass[a5paper,article,12pt]{memoir}

% Marges
\setulmarginsandblock{1.5cm}{1.5cm}{*}
\setlrmarginsandblock{1.5cm}{1.5cm}{*}
\checkandfixthelayout
\setlength{\parindent}{0in}

% Kop- en voettekst
\makeheadrule{headings}{\textwidth}{\normalrulethickness}
\makefootrule{ruled}{\textwidth}{\normalrulethickness}{\footruleskip}

\makeevenfoot{headings}{\thepage}{}{}
\makeoddfoot{headings}{}{}{\thepage}
\makeevenhead{headings}{\leftmark}{}{}
\makeoddhead{headings}{}{}{\rightmark}

\makeheadrule{headings}{\textwidth}{\normalrulethickness}
\makefootrule{ruled}{\textwidth}{\normalrulethickness}{\footruleskip}

\makeevenhead{headings}{\leftmark}{}{}
\makeevenhead{ruled}{\leftmark}{}{}
\pagestyle{ruled}

\copypagestyle{chapter}{plain}
\makeevenfoot{chapter}{\thepage}{}{}
\makeoddfoot{chapter}{}{}{\thepage}
\makeevenhead{chapter}{}{}{}
\makeoddhead{chapter}{}{}{}

\makefootrule{chapter}{\textwidth}{\normalrulethickness}{\footruleskip}

\renewcommand\chaptermarksn[1]{}
\renewcommand\sectionmarksn[1]{}

% Vormgeving
\usepackage{fontspec}
\setmainfont{Times New Roman} %lettertype
\usepackage{graphicx}
\usepackage[utf8]{inputenc} % speciale tekens
\usepackage[dutch]{babel} 

\usepackage{lyluatex}

\begin{document}

% title page
\thispagestyle{empty}

\begin{center}

\Large {Orde van Dienst }   \\
\Huge \textbf{Dienst van Eerste Kerstdag } \\

                                                \vspace{\fill}
\includegraphics{voorplaat20191225.jpg} 
         \vspace{\fill}

\Large{ Dorpskerk Berkenwoude} \\
\Large{ 25 december 2019 } 

\end{center}
\vspace{\fill}

\newpage

Voorganger: (NAME) \\
Ouderling: (NAME)\\
Diaken: (NAME) \\
Ouderling-Kerkrentmeester: (NAME) \\
Organist: (NAME) \\
met medewerking van: \\
Cantorij onder leiding van (NAME) \\
Groep Liturgisch Bloemschikken
\vspace{\fill}

De foto op de voorplaat toont de parochiekerk van het Oostenrijkse dorp Wagrain. In deze kerk was de dichter van Stille Nacht, Joseph Mohr, in de negentiende eeuw enige tijd kapelaan. Hij ligt op het plaatselijke kerkhof begraven.
\newpage

\textbf{Orgelspel} 
\vspace{8pt}

\textbf{Welkom en mededelingen} 
\vspace{8pt}

\textbf{Moment van stilte} 
\vspace{8pt}

\textbf{Zingen: Hoor de eng'len zingen d'eer} 
\vspace{8pt}

1. Hoor, de eng'len zingen d'eer 
van de nieuw geboren Heer! \\
Vreed op aarde, 't is vervuld: 
God verzoent der mensen schuld. \\
Voegt u, volken, in het koor, 
dat weerklinkt de hemel door, \\
zingt met algemene stem 
voor het kind van Bethlehem! \\
 Hoor, de eng'len zingen d'eer 
van de nieuw geboren Heer! 
\vspace{8pt}

2 . Hij, die heerst op 's hemels troon, 
Here Christus, Vaders Zoon, \\
wordt geboren uit een maagd 
op de tijd die God behaagt. \\
Zonne der gerechtigheid, 
woord dat vlees geworden zijt, \\
tussen alle mensen in 
in het menselijk gezin. \\
 Hoor, de eng'len zingen d'eer 
van de nieuw geboren Heer! 
\vspace{8pt}

3. Lof aan U die eeuwig leeft 
en op aarde vrede geeft, \\
Gij die ons geworden zijt 
taal en teken in de tijd, \\ 
al uw glorie legt Gij af 
ons tot redding uit het graf, \\
dat wij ongerept en rein 
nieuwgeboren zouden zijn. \\
 Hoor, de eng'len zingen d'eer 
van de nieuw geboren Heer! 
\vspace{8pt}

\textbf{Votum en groet} 
\vspace{8pt}

\textbf{Aansteken kerstkaars en gedicht} 
\vspace{8pt}

De nacht is nog niet opgeklaard, \\
het lied van de engelen verstomd \\
en ver te zoeken op aarde \\
is de vrede. 
\vspace{8pt}

Maar nog altijd niet \\
is de vlam gedoofd, \\
die ene wankele vlam, \\
die brandde in een pasgeboren kind,
\vspace{8pt}

en wij koesteren die vlam, \\
warmen ons aan haar \\
en geven haar rond \\
met alle liefde.
\vspace{8pt}

\textbf{De cantorij zingt: Lasst uns nach Bethlehem gehen.} \\
Een kerstlied uit Karinthië
\vspace{8pt}

1. Laten we naar Bethlehem gaan, \\
daar is een wonder te zien. \\
Wat moet dat betekenen, \\
dat er zoveel mensen, \\
een groot aantal, daar staan?
\vspace{8pt}

2. Wij hebben vandaag vernomen, \\
voor ons is de Messias gekomen, \\ 
in een eenvoudig oord,  \\
in een stal ligt Hij daar, \\
heeft Hij zijn intrek genomen.
\vspace{8pt}

3. In een stal, in het hooi ligt de Koning, \\
maakt de wereld onderaan, \\
die woont in het hemelrijk, \\
aan zijn Vader gelijk, \\
heeft hier te weinig dekentjes. 
\vspace{8pt}

4. Ach, wat een vreugde zal het zijn, \\
als wij Gods rijk ingaan, \\
van alle gevaar bevrijd, \\
in alle eewigheid \\
God, onze Vader, te zien. 
\vspace{8pt}

\textbf{Gebed in de Kerstmorgen} 
\vspace{\fill}

\newpage

\textbf{Zingen: Zeg eens, herder, waar kom jij vandaan?}
\vspace{8pt}

\begin{ly}
\version "2.18.2"

#(define-public (format-time-sig-note grob)
(let* ((frac (ly:grob-property grob 'fraction))
(num (if (pair? frac) (car frac) 4))
(den (if (pair? frac) (cdr frac) 4))
(m (markup #:override '(baseline-skip . 0.5)
#:center-column (#:number (number->string num)
#:override '(style . default)
#:note (number->string den) DOWN))))
(grob-interpret-markup grob m)))

\paper {

}

global =  {

	\time 2/4
	\key g \major

}

melody = \relative c'' { \global
 \autoBeamOff
	g4 b4 a8 fis8 g8 d8 g4 b4 a2 \break
	d,8 d8 e8 fis8 g4 d4 g8 g8 a8 b8 a2 \break
	d,8 d8 e8 fis8 g4 d4 g8 b8 a8 a8 g2 \bar "|."

}

words = \lyricmode { \set stanza = #"1. "
Zeg eens, her -- der, waar kom jij van -- daan? 
Ik heb eens ge -- ke -- ken in een ou -- de stal,
daar zag ik een won -- der, dat `k_ver -- tel -- len zal.

}

\score { 
	<<
	\new Staff { \melody }
	\addlyrics { \words }
	>>
	\layout { 
		\context { \Score
			\remove "Bar_number_engraver"
		}
	}
}
\end{ly}
\vspace{8pt}

2. Zag eens wat heb jij gezien? \\
Ik zag een os en ezel bij een voederbak, \\
het was er koud en donker, tocht kwam door het dak.
\vspace{8pt}

3. Zeg eens herder zag je daar nog meer? \\
Ja ik zag een kindje schreiend van de kou \\
en daarbij stond Jozef die het warmen wou.
\vspace{8pt}

4. Zeg eens herder zag je soms nog meer? \\
Ik zag toen dat Maria het kind in de armen nam, \\
os en ezel keken, ook een heel klein lam.
\vspace{8pt}

5. Zeg eens herder is het lief en schoon? \\
Schoner dan het zonlicht, schoner dan de maan, \\
schoner dan de hemel waar de sterren staan.
\vspace{8pt}

6. Zeg eens herder heeft het iets gevraagd? \\
Ja het vroeg om liefde, schatten wou het geen, \\
laat wij nu allen, gaan tot Hem alleen.
\vspace{8pt}

\textbf{Aandacht voor de kinderen en adventsproject: Geef licht!} 
\vspace{\fill}

\newpage

\textbf{Zingen: projectlied} 
\vspace{8pt}

\begin{ly}
\version "2.18.2"

#(define-public (format-time-sig-note grob)
(let* ((frac (ly:grob-property grob 'fraction))
(num (if (pair? frac) (car frac) 4))
(den (if (pair? frac) (cdr frac) 4))
(m (markup #:override '(baseline-skip . 0.5)
#:center-column (#:number (number->string num)
#:override '(style . default)
#:note (number->string den) DOWN))))
(grob-interpret-markup grob m)))

\paper {

}

global =  {

	\time 4/4
	\key f \major

}

melody = \relative c'' { \global
 \autoBeamOff
	f,4. g8 a4 g4 f4 d4 c2 d4. e8 f4 g4 a4 c4 g2 \break
	bes4. a8 g4 bes4 a4 g4 f2 g4. g8 a4 f4 g4 c4 c2 \break
	r2 r4 a4 c2 r4 a4 c2 r4 f,4 g4. g8 a4 bes4 \break
	a4 g4 f2 g4. bes8 a8 g8 f8 e8 f2. r4  \bar "|."

}

words = \lyricmode { \set stanza = #"1. "
In het don -- ker van de nacht
zingt de he -- mel men -- sen voor.
Zie het licht en geef het door.
Zo geeft God je le -- vens -- kracht

Geef licht, geef licht!
Je krijgt het gratis,
niet voor niets.
Zorg dat ie -- der -- een het ziet.

}

\score { 
	<<
	\new Staff { \melody }
	\addlyrics { \words }
	>>
	\layout { 
		\context { \Score
			\remove "Bar_number_engraver"
		}
	}
}
\end{ly}
\vspace{8pt}

\begin{tabular}{ l l} 
2. In het kleine Bethlehem & Geef licht, geef licht! \\
krijgt Gods liefde een gezicht. & Je krijgt het gratis, \\
Hij brengt vrede, hoop en licht. & niet voor niets. \\
Ga op weg, dan vind je hem! & Zorg dat iedereen het ziet.
\end{tabular}
\vspace{8pt}

\textbf{Gebed bij de opening van de schrift} 
\vspace{8pt}

\textbf{Eerste lezing: Jesaja 53: 1-4, 11} 
\vspace{8pt}

Als een loot schoot hij op onder Gods ogen,
als een wortel die uitloopt in dorre grond.
Onopvallend was zijn uiterlijk,
Hij miste iedere schoonheid,
zijn uiterlijk kon ons niet bekoren.
Hij werd veracht, door mensen gemeden,
Hij was een man die het lijden kende
en met ziekte vertrouwd was,
een man die zijn gelaat voor ons verborg,
veracht, door ons verguisd en geminacht.
Na het lijden dat hij moest doorstaan,
zag hij het licht en werd met kennis verzadigd.
\vspace{8pt}

\textbf{Zingen: Er is een roos ontloken} 
\vspace{8pt}

1. Er is een roos ontloken 
uit barre wintergrond, \\
zoals er was gesproken  
door der profeten mond. \\
En Davids oud geslacht  
is weer opnieuw gaan bloeien \\
in 't midden van de nacht.
\vspace{8pt}

2. Die roos van ons verlangen,  
dat uitverkoren zaad, \\
is door een maagd ontvangen 
uit Gods verborgen raad. \\
Maria was bereid,  
toen Gabriël haar groette \\ 
in 't midden van de tijd.
\vspace{8pt}

3. Die bloem van Gods behagen 
heeft, naar Jesaja sprak, \\
de winterkou verdragen  
als allerdorste tak. \\
O roos als bloed zo rood, 
God komt zijn volk bezoeken \\
in 't midden van de dood.
\vspace{8pt}

\textbf{Tweede lezing: Johannes 1:1-18} 
\vspace{8pt}

In het begin was het Woord, het Woord was bij God en het Woord was God. Het was in het begin bij God. Alles is erdoor ontstaan en zonder dit is niets ontstaan van wat bestaat. In het Woord was leven en het leven was het licht voor de mensen. Het licht schijnt in de duisternis en de duisternis heeft het niet in haar macht gekregen.
Er kwam iemand die door God was gezonden; hij heette Johannes. Hij kwam als getuige, om van het licht te getuigen, opdat iedereen door hem zou geloven. Hij was niet zelf het licht, maar hij was er om te getuigen van het licht; het ware licht, dat ieder mens verlicht en naar de wereld kwam.
Het Woord was in de wereld, de wereld is door hem ontstaan en toch kende de wereld hem niet. Hij kwam naar wat van hem was, maar wie van hem waren hebben hem niet ontvangen. Wie hem wel ontvingen en in zijn naam geloven, heeft hij het voorrecht gegeven om kinderen van God te worden. Zij zijn niet op natuurlijke wijze geboren, niet uit lichamelijk verlangen of uit de wil van een man, maar uit God.
Het Woord is mens geworden en heeft bij ons gewoond, vol van goedheid en waarheid, en wij hebben zijn grootheid gezien, de grootheid van de enige Zoon van de Vader. Van hem getuigde Johannes toen hij uitriep: ‘Hij is het over wie ik zei: “Die na mij komt is meer dan ik, want hij was er vóór mij!”’ Uit zijn overvloed zijn wij allen met goedheid overstelpt. De wet is door Mozes gegeven, maar goedheid en waarheid zijn met Jezus Christus gekomen. Niemand heeft ooit God gezien, maar de enige Zoon, die zelf God is, die aan het hart van de Vader rust, heeft hem doen kennen.
\vspace{8pt}

\textbf{Cantorij en gemeente zingen: In het begin was `t Woord} \\
Es wår a stille Nåcht 
\vspace{8pt}

\textit{Cantorij} \\
1. In het begin was ’t Woord. \\
Op aarde werd gehoord \\
een stem, die sprak tot elk geslacht, \\
een woord, dat licht en leven bracht, \\
het licht schijnt in de nacht, \\
het licht schijnt in de nacht,
\vspace{8pt}

\begin{tabular}{ l l} 
2. God zond een vreemde man & 3. Het Woord kwam in de nacht \\ 
en die getuigde van & ter wereld, zonder macht. \\
het licht dat in de wereld is, & De wereld is door 't Woord ontstaan, \\
hoor naar zijn groot getuigenis, & maar wist toch niet van zijn bestaan, \\
Johannes is zijn naam, &  het Woord werd niet herkend, \\
Johannes is zijn naam. & het Woord werd niet herkend.
\end{tabular}
\vspace{8pt}

\textit{Gemeente}
\begin{ly}
\version "2.18.2"

#(define-public (format-time-sig-note grob)
(let* ((frac (ly:grob-property grob 'fraction))
(num (if (pair? frac) (car frac) 4))
(den (if (pair? frac) (cdr frac) 4))
(m (markup #:override '(baseline-skip . 0.5)
#:center-column (#:number (number->string num)
#:override '(style . default)
#:note (number->string den) DOWN))))
(grob-interpret-markup grob m)))

\paper {

}

global =  {

	\time 3/4
	\key f \major
	\partial 4

}

melody = \relative c'' { \global
 \autoBeamOff
f,4 f2 f4 g2 g4 a2. (a2) \bar "" \break
a4 c2 c4 a2 a4 g2. (g2) \bar "" \break
g4 g2 g4 bes2 bes4 a2 a4 f2 \bar "" \break
a4 bes2 bes4 d2 d4 c2 c4 a2 \bar "" \break
a4 g2 g4 bes2 bes4 a2. (a2) \bar "" \break
a4 f2 f4 f2 f4 f2 \bar "|."

}

words = \lyricmode { \set stanza = #"4. "
Maar wie ge -- looft in Hem
en luis -- tert naar zijn stem,
wie met Jo -- han -- nes Je -- zus roemt,
die wordt een kind van God ge -- noemd,
die is uit God op aard’,
die is uit God op aard’. 

}

\score { 
	<<
	\new Staff { \melody }
	\addlyrics { \words }
	>>
	\layout { 
		\context { \Score
			\remove "Bar_number_engraver"
		}
	}
}
\end{ly}
\vspace{8pt}
5. Het Woord, dat werd een mens, \\
getuigde, naar Gods wens, \\
bij ons van waarheid, heerlijkheid. \\
Johannes heeft zijn weg bereid: \\
“Wie na mij komt, is meer, \\
wie na mij komt, is meer.”
\vspace{8pt}

6. Na Mozes' wet kwam ’t Woord: \\
genade werd gehoord. \\
Geen mens heeft ooit God zelf aanschouwd \\
maar Jezus heeft zijn heil ontvouwd \\
en maakt het ons bekend, \\ 
en maakt het ons bekend.
\vspace{8pt}

\textbf{Verkondiging} 
\vspace{\fill}

\newpage

\textbf{Zingen: Komt, verwondert u hier, mensen} 
\vspace{8pt}

1. Komt, verwondert u hier, mensen,
ziet, hoe dat u God bemint, \\
ziet vervuld der zielen wensen,
ziet dit nieuw geboren kind! \\
Ziet, die 't woord is, zonder spreken,
ziet, die vorst is, zonder pracht, \\
ziet, die 't al is, in gebreken,
ziet, die 't licht is, in de nacht, \\
ziet, die 't goed is, dat zo zoet is,
wordt verstoten, wordt veracht.
\vspace{8pt}

4. O Heer Jesu, God en mense,
die aanvaard hebt deze staat, \\
geef mij wat ik door U wense,
geef mij door uw kindsheid raad. \\
Sterk mij door uw tere handen,
maak mij door uw kleinheid groot, \\
maak mij vrij door uwe banden,
maak mij rijk door uwe nood, \\
maak mij blijde door uw lijden,
maak mij levend door uw dood!
\vspace{8pt}

\textbf{Dank- en voorbeden, stil gebed en Onze Vader} 
\vspace{8pt}

\textbf{De cantorij zingt: Diep in de nacht} \\
Andachtsjodler 
\vspace{8pt}

Diep in de nacht - in de stille nacht -\\
klonk onverwacht - in de heil'ge nacht -  \\
een eng'lenkoor - eng'lenkoor - dat zong uit alle macht: \\
Ere zij God, ere zij God, \\
ere zij God en vrede op aard'. \\
Jezus is geboren in een stal, \\
in de stad van koning David, \\
Hij die alle volken, overal ter wereld, \\
eens verlossen zal.  \\
Ere zij God, ere zij God, \\
ere zij God en vrede op aard'.
\vspace{8pt}

\textbf{Collecte}
\vspace{8pt}

\textbf{Ere zij God }
\vspace{8pt}

Ere zij God, ere zij God in de hoge, in de hoge, in de hoge. \\
Vrede op aarde, vrede op aarde, in de mensen een welbehagen. \\
Ere zij God in de hoge. Ere zij God in de hoge. \\
Vrede op aarde, vrede op aarde, \\
vrede op aarde, vrede op aarde, \\
in de mensen, in de mensen een welbehagen, \\
in de mensen een welbehagen, een welbehagen. \\
Ere zij God, ere zij God, in de hoge, in de hoge, in de hoge.\\
Vrede op aarde, vrede op aarde, in de mensen een welbehagen. \\
Amen, amen.
\vspace{8pt}

\textbf{Zegen}
\vspace{8pt}

\textbf{Orgelspel}
\vspace{8pt}

\newpage

\textbf{Diensten in de Kersttijd } 
\vspace{8pt}

Zondag 29 december, 10:00 uur \\ 
Dienst van de Zondag na Kerstmis \\
(NAME)
\vspace{8pt}

Dinsdag 31 december, 10:00 - 12:00 uur \\
Ontmoeting op Oudejaarsdag 
\vspace{8pt}

Dinsdag 31 december, 18:30 uur \\
Vesper van Oudejaarsdag \\
(NAME)
\vspace{8pt}

Op Oudejaarsdag zijn er tussen 8:30 en 12:00 uur weer verse oliebollen te koop bij de Dorpskerk. 
\vspace{8pt}
 
 
\begin{center}
\includegraphics{achterplaat20191225.jpg} 
\end{center}

\end{document}

**Comment by uliska** [comment]
I think it would be extremely helpful if you could boil this down to a "Minimal Working Example", i.e. the smallest possible document that exposes the problem. Actually you didn't tell us what the problem is.

**Comment by Brayanokles** [comment]
The problem lays in the Lilypond part. 

\documentclass[a5paper,article,12pt]{memoir}

% Marges
\setulmarginsandblock{1.5cm}{1.5cm}{}
\setlrmarginsandblock{1.5cm}{1.5cm}{}
\checkandfixthelayout
\setlength{\parindent}{0in}

% Kop- en voettekst
\makeheadrule{headings}{\textwidth}{\normalrulethickness}
\makefootrule{ruled}{\textwidth}{\normalrulethickness}{\footruleskip}

\makeevenfoot{headings}{\thepage}{}{}
\makeoddfoot{headings}{}{}{\thepage}
\makeevenhead{headings}{\leftmark}{}{}
\makeoddhead{headings}{}{}{\rightmark}

\makeheadrule{headings}{\textwidth}{\normalrulethickness}
\makefootrule{ruled}{\textwidth}{\normalrulethickness}{\footruleskip}

\makeevenhead{headings}{\leftmark}{}{}
\makeevenhead{ruled}{\leftmark}{}{}
\pagestyle{ruled}

\copypagestyle{chapter}{plain}
\makeevenfoot{chapter}{\thepage}{}{}
\makeoddfoot{chapter}{}{}{\thepage}
\makeevenhead{chapter}{}{}{}
\makeoddhead{chapter}{}{}{}

\makefootrule{chapter}{\textwidth}{\normalrulethickness}{\footruleskip}

\renewcommand\chaptermarksn[1]{}
\renewcommand\sectionmarksn[1]{}

% Vormgeving
\usepackage{fontspec}
\setmainfont{Times New Roman} %lettertype
\usepackage{graphicx}
\usepackage[utf8]{inputenc} % speciale tekens
\usepackage[dutch]{babel}

\usepackage{lyluatex}

\begin{document}

\begin{ly}
\version "2.18.2"

#(define-public (format-time-sig-note grob)
(let* ((frac (ly:grob-property grob 'fraction))
(num (if (pair? frac) (car frac) 4))
(den (if (pair? frac) (cdr frac) 4))
(m (markup #:override '(baseline-skip . 0.5)
#:center-column (#:number (number->string num)
#:override '(style . default)
#:note (number->string den) DOWN))))
(grob-interpret-markup grob m)))

\paper {

}

global = {

\time 2/4
\key g \major
}

melody = \relative c'' { \global
\autoBeamOff
g4 b4 a8 fis8 g8 d8 g4 b4 a2 \break
d,8 d8 e8 fis8 g4 d4 g8 g8 a8 b8 a2 \break
d,8 d8 e8 fis8 g4 d4 g8 b8 a8 a8 g2 \bar "|."

}

words = \lyricmode { \set stanza = #"1. "
Zeg eens, her -- der, waar kom jij van -- daan?
Ik heb eens ge -- ke -- ken in een ou -- de stal,
daar zag ik een won -- der, dat `k_ver -- tel -- len zal.

}

\score {
<<
\new Staff { \melody }
\addlyrics { \words }
>>
\layout {
\context { \Score
\remove "Bar_number_engraver"
}
}
}
\end{ly}

\end{document}

In Texlive 2018 it was working nicely, but in Texlive 2020 it's not.

**Comment by jperon** [comment]
Hello,

The first document you gave worked for me after I:

- commented `\includegraphics{...}` as I didn't have the images ;
- replaced `\` by `\\` in tabulars.

So in that one, the problem didn't come from the lilypond part.

The second document you gave had an error in the lilypond code : there was a missing `>>` in the `\score` block, after `\addlyrics { \words }` :
```
\score {
<<
	\new Staff { \melody }
	\addlyrics { \words }
>> %%%%%% missing
	
	\layout {
		\context { \Score
			\remove "Bar_number_engraver"
		}
	}
}
```

**Comment by uliska** [comment]
These comments strongky point to the need of a real MWE.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Brayanokles** [comment]
What do you mean with MWE?

**Comment by rpspringuel** [comment]
https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that

**Comment by Brayanokles** [comment]
Thanks for the help, it seems to be working again.
