### ISSUE TITLE
Fatal error: missing \begin{document} 

### ISSUE THREAD

**Issue by Brayanokles** [jperon/lyluatex#278]
I tried to make a new booklet. I created this imput: 

\documentclass[a5paper,article,12pt]{memoir}

\usepackage{lyluatex}

\begin{document}

% title page
\thispagestyle{empty}

\begin{center}

Dit is het begin

\vspace{\fill}

\newpage

\end{document}

In Lualatex I got this: 

_This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/W32TeX) 
 system commands enabled.
("./Nieuw Praiosliedboek.tex"
LaTeX2e <2020-02-02> patch level 5
 L3 programming layer <2020-04-06>
(c:/texlive/2020/texmf-dist/tex/latex/memoir/memoir.cls
Document Class: memoir 2020/03/25 v3.7k configurable book, report, article docu
ment class
(c:/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty)
(c:/texlive/2020/texmf-dist/tex/latex/memoir/mem12.clo)
(c:/texlive/2020/texmf-dist/tex/latex/tools/array.sty)
(c:/texlive/2020/texmf-dist/tex/latex/tools/dcolumn.sty)
(c:/texlive/2020/texmf-dist/tex/latex/tools/delarray.sty)
(c:/texlive/2020/texmf-dist/tex/latex/tools/tabularx.sty)
(c:/texlive/2020/texmf-dist/tex/latex/textcase/textcase.sty)) (./lyluatex.sty

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 <
   !DOCTYPE html>
?_ 

What did I do wrong?

**Comment by jperon** [comment]
I don't get the same error with that one : the error message seems to indicate something before `\begin{document}` that should be after. Wouldn't you have spurious spaces or other special characters in lines 1 to 5 ?

That said, I do get an error with the document as is : there is a missing `\end{center}`. The document should be :

```latex
\documentclass[a5paper,article,12pt]{memoir}
\usepackage{lyluatex}

\begin{document}

% title page
\thispagestyle{empty}

\begin{center}
Dit is het begin
\end{center}

\vspace{\fill}

\newpage

\end{document}
```

Just a tip : when you copy/paste some code, you should surround it with ``` before and after, to get a code box like above. You may even add `latex` after the first backticks, to get syntax color.

**Comment by Brayanokles** [comment]
Thanks for your reply.
This was the only text I put into this file. The \end{center} is in the document now, but I still get the same error.

I tried this one:

\documentclass[a5paper,article,12pt]{memoir}

\usepackage{lyluatex}

\begin{document}

Dit is het begin

\newpage

\end{document}

Same result.

**Comment by uliska** [comment]
@jperon do you already run tl20? I recall someone having a steange problem with LuaHBsomething (HarfBuzz). Maybe there's indeed a problem with new Lua tools?

**Comment by jperon** [comment]
Here is what I get when calling `lualatex` :

```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Debian) 
 system commands enabled.
(./test.tex
LaTeX2e <2020-02-02> patch level 5
 L3 programming layer <2020-03-06>
```

I'm not on vanilla TeXLive, but on the version found on Debian sid.

**Comment by Brayanokles** [comment]
Would it be a good idea, reinstalling TL2018?

**Comment by jperon** [comment]
Or 2019, waiting for a fix, if you can have both in parallel… But if there's a bug, I'd like to fix it ! Could you please try a cut-paste from [this message](https://github.com/jperon/lyluatex/issues/278#issuecomment-615932235) into a new document, and compile it ?

**Comment by Brayanokles** [comment]
I put it into another folder and now it seems to work. How is that possible?

**Comment by jperon** [comment]
Just guessing, but it could be a non-printable character (unbreakable space or such), or perhaps an encoding problem (utf-8 vs other) ? Whatever be it, I'll close those issues ; feel free to re-open (or open new ones) if there are other problems.

**Comment by Brayanokles** [comment]
Thank you for your help and a blessed Easter.

**Comment by jperon** [comment]
Blessed Easter to you !
