### ISSUE TITLE
system-by-system integration

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#28]
There should be a command that inserts a score as a sequence of systems interspersed with some glue space (like lilypond-book does). This will allow multi-system scores to flow over page breaks.

The individual system PDFs are already there in the temp directory anyway ...

**Comment by jperon** [comment]
This is the default behaviour : as you  may see in `write_tex` function (l. 157), the content of `OUTPUT-systems.tex` is used, which is the same as lilypond-book.
When one calls `\includely` with the `fullpage=true` option, the function `lilypond-file` overwrites the content of `OUTPUT-systems.tex` with a call to the full pdf.

**Comment by mhohl** [comment]
Am 15.01.2018 um 15:58 schrieb Urs Liska:
> There should be a command that inserts a score as a sequence of systems 
> interspersed with some glue space (like lilypond-book does). This will 
> allow multi-system scores to flow over page breaks.
> 
> The individual system PDFs are already there in the temp directory 
> anyway ...

Isn't that exactly what \betweenLilyPondSystem is supposed to do?
Or do you want to have some sensible defaults?

Marc

**Comment by uliska** [comment]
@jperon 
> This is the default behaviour : as you may see in write_tex function (l. 157), the content of OUTPUT-systems.tex is used, which is the same as lilypond-book.

Thank you,  I didn't see that. Sorry for the noise, but with many parts of these equations I'm not too familiar.

@mhohl 
> Isn't that exactly what \betweenLilyPondSystem is supposed to do?
> Or do you want to have some sensible defaults?

Yes and yes. I want both, sensible defaults and the ability to override it like in lilypond-book.

**Comment by jperon** [comment]
For now, I think that, on that point, `lyluatex` does exactly what `lilypond-book` does : I must confess that what I did here was just to cut/paste code from it !

**Comment by uliska** [comment]
Yes, and that's fine. What I think we need in addition is support for `betweenLilyPondSystem`, a flexible, overridable "glue" that is placed between every two systems in lilypond-book. There's the conditional to only use it if it's defined, which is the reason it doesnt disturb the working of lyluatex.
