### ISSUE TITLE
cannot start lilypond

### ISSUE THREAD

**Issue by pcouderc12** [jperon/lyluatex#284]
using debian bullseye. Standard texlive and lilypons installed by apt install.

lilypond is not found.
I have tried 
\usepackage{lyluatex}
\lyOption{program}{/usr/bin/lilypond}

but I get an error...
Thanks for help.
PC

**Comment by jperon** [comment]
Sorry for the (huge!) delay : I hadn't seen the notification for your issue. Is this problem still there ? May you please send me the output of `lualatex` if so ?

**Comment by pcouderc12** [comment]
Mmm, sorry, I have forgotten the need, certainly I wanted to mix lilypond and gregorio...
Merci !
PC

**Comment by jperon** [comment]
It should be possible : https://musite.prn.ovh/fr/Documentation/exemples/Magnificat.tex
Feel free to send me a log if you encounter any error again !

**Comment by pcouderc12** [comment]
Sure, thank you very much !
