### ISSUE TITLE
Latex Error: ./filename.tex:62 Too many }'s.

### ISSUE THREAD

**Issue by eefweenink** [jperon/lyluatex#288]
In my texfile a line like this:

\lilypondfile[staffsize=10]{/Lilypondfiles/exmp001.ly} 

It always gives me this error (also whith the most simple textfile I use). 
Latex Error: ./filename.tex:62 Too many }'s.     
Everywhere I search the number of {} is correct.  (no error with compiling in lilypond). 

Any suggestions how to solve this? Regards.

**Comment by jperon** [comment]
Thank you for your report.
May you please send me : 

- more details about your environment (Windows / Linux / MacOs ? TeXLive / MikTeX ?) ;
- a "minimal (non) working example", either by [mail](mailto:cataclop@hotmail.com), or by using the code tags of github ? For example :

```latex
\documentclass{article}
\usepackage{lyluatex}
\begin{document}
\lilypond{a b c}
\end{document}
```

**Comment by eefweenink** [comment]
Dear Fr. Jacques Peron, 

I found the error. There was an extra }. It showed up, when building the minimal version. (Apologies. I should have found it myself. I had been searching for hours, making new versions, etcetera and kept showing up as an error). 

Merci for the help, because without your question to make a minimal version, I don't think I would have ever found it. 

Regards, Eef Weenink

**Comment by jperon** [comment]
You’re welcome ! Feel free to ask if you encounter other problems.
