### ISSUE TITLE
Also enforce layout of fullpage scores

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#29]
If I'm not mistaken when a LilyPond file is included and `fullpage` is requested it is compiled as defined in the file itself.

However, we should also set the margins for the score according the the geometry of the text document. I think for this we should split `lilypond_fragment_header` into two separate functions, one injecting the system-by-system compilation behaviour (for fragments) and the other defining the `\paper` block, which would also be used for fullpage scores. I have checked that it is possible to append a paper block and staffsize settings to the end of a LilyPond file to override any earlier settings.

Defining the layout of fullpage scores is more involved, as the line width isn't the only relevant parameter anymore, we also have the four margins. And there should also be the differentiation between one- and two-page layout. Probably we should also try to figure out if the full-page score will start on an odd or even page and set the "first-page-number" accordingly.

However, it should be considered/discussed how inserting fullpage scores relates to the corresponding command in `musicexamples`. With all the fragment commands it is clear: they can simply be *wrapped* by the musicexamples environments, but this is a somewhat different case as (so far) musicexamples implements this as a *command*, not an *environment*.

**Comment by uliska** [comment]
I think this is now quite important. With every new option we implement fragments and fullpage examples drift further away from each other.

**Comment by jperon** [comment]
I think I'm going to work on #46, and that those two issues are related. Would you like me to take hand on this one too ?

But I think that, before beginning that, we have to merge existing pull requests.

**Comment by uliska** [comment]
>  think I'm going to work on #46, and that those two issues are related. Would you like me to take hand on this one too ?

That would be nice, I don't have any specific urge to do that myself.

> But I think that, before beginning that, we have to merge existing pull requests.

Yes, definitely. The nature of our code makes merge conflicts far more probable than average.

**Comment by uliska** [comment]
Closed via #48

**Comment by jperon** [comment]
I'd let this one open, as the layout isn't "fully" enforced (margins).

**Comment by jperon** [comment]
#52 advances on solving this issue.

**Comment by uliska** [comment]
Even with #52 merged I'd like to keep this one open as there is yet another issue that may improve the layout results.

What we're aiming at is matching the type area of inserted fullpage scores with that of the text document.

What we have achieved so far is

* match the four `margin` properties
* take "protrusion" into account. While this hasn't fully been resolved (that's the next thing I'll turn back to) we have a good understanding of what we're talking about

What is completely open is the behaviour of the vertical margins.
Setting these margins in LilyPond is totally not straightforward (actually similar to how it is in LaTeX - but we start from a given type area in LaTeX).

I *think* what we should achieve as default behaviour is to match the *outermost staffline* with the margins of the text document. I *think* this is what defines the visual impression of a "type area" in a score.

So my suggestion is to determine the proper way to setting LilyPond to match the "margin-up-to-the-outer-staffline" and use that as the default settings for the score.
This will also provide the best results together with LaTeX's headers and footers.
The user may then locally override that default if the score has elements that reach too far into the top or bottom margin.

What do you think @jperon  and @rpspringuel ?

**Comment by uliska** [comment]
I *think* that we have to determine the following values:

For the top margin:
* set `margin-top` to `0`
* determine the value of our desired margin in staff spaces
* set `top-system-spacing` and `top-markup-spacing` to a value (`basic-distance`, everything else to `0`),
`last-bottom`too

**Comment by rpspringuel** [comment]
Since I don't include full-/multi-page scores in my documents, I'm not in a position to discuss this based on theory or past experience.  If you can post samples of the options, I can comment on those.

**Comment by uliska** [comment]
This is a sample of the current default result. First the overview of the double page:
![image](https://user-images.githubusercontent.com/1812148/35497565-e980dbf6-04ca-11e8-8e34-3df990d0b51c.png)


Then a detail of the top-margin:
![image](https://user-images.githubusercontent.com/1812148/35497513-be3bc118-04ca-11e8-8746-d2e432a53115.png)

As one can see the top margin of the text area is aligned with the top-most item in the score. Instead I would suggest to align the text with the top-most *staff-line* by default. If the score "protrudes" too much into the top margin (for example with an ottava or very high notes or markups) the user should be able to override the behaviour (presumably on a local basis) with some `extra-top-margin` or by forcing the current behaviour of aligning to the top-most *element*.

If on the other hand there is titling at the top I think it's perfectly OK to align it as it is now. I think (hope) this is what can be achieved by setting both `top-system-spacing` and `top-markup-spacing`:
![image](https://user-images.githubusercontent.com/1812148/35497810-111e1ba0-04cc-11e8-98a1-f4648ebe848e.png)

---

However, the *bottom* margin is completely off and nearly runs into the page number. Here we have to check for *two* parameters: first I think the calculation as it is now misses some length, but the other is that LilyPond's bottom-margin also doesn't care for the last staffline but the actual printed items. That means that when there are low notes or pedal marks the lowest system shifts up.

**Comment by uliska** [comment]
This is what I *think* it should look like (achieved through manually setting the vertical margins by trial & error). The bottom margin of the text is aligned with the lowest staff line, and the highest staff line is aligned with the *x height* of the first line of text, which seems to look more natural than the actual top margin of the text.
*Maybe* there's something to be discussed about the bottom aligment. Somehow it feels like the lowest staff line is too low  here, even if it is geometrically aligned. Maybe one should add a tiny amount of padding here? But I'm reluctant to suggest some *arbitrary* value (different from the top where one can conveniently use the x height as a reference).

![image](https://user-images.githubusercontent.com/1812148/35498550-1780de08-04cf-11e8-9553-2bb1aabbe33e.png)

**Comment by jperon** [comment]
I've just corrected the problem with the bottom margin.
About the suggestions concerning protrusion into top margin, I think it should be defined as an *opt-in* option, not as the default, to avoid unexpected problems.

**Comment by uliska** [comment]
I'll give a shot and determine the correct point values and overrides for the vertical alignment, without deciding about default behaviour.

**Comment by uliska** [comment]
Closed with #54
