### ISSUE TITLE
Lyluatex fails to compile documents in GitHub Actions

### ISSUE THREAD

**Issue by Witiko** [jperon/lyluatex#295]
At [witiko/lyluatex-github-actions-example][1], I created a simple MWE that shows Lyluatex [failing in GitHub Actions][2]:

```
(lyluatex)	Compiling score tmp-ly/7140c4bbdb90291190558426f58d61bd with LilyPond executable 'lilypond'.
fatal error: cannot rename `7140c4bbdb90291190558426f58d61bd.eps.356991.pdf' to `7140c4bbdb90291190558426f58d61bd.pdf'
Module lyluatex Warning: The score doesn't contain any music:
(lyluatex)               this will probably cause bad output. on input line 13
...ocal/texlive/2022/texmf-dist/tex/latex/base/ltluatex.lua:110: 
Module lyluatex Error: 
(lyluatex)             LilyPond failed to compile the score.
(lyluatex)             Please check the log file
(lyluatex)             and the generated LilyPond code in
(lyluatex)             tmp-ly/7140c4bbdb90291190558426f58d61bd.log
(lyluatex)             tmp-ly/7140c4bbdb90291190558426f58d61bd.ly
(lyluatex)             
(lyluatex)             on input line 13
```

I have been using GitHub Actions to typeset LaTeX documents for several years now and I have never encountered an error like this. Do you have any idea what the issue could be? I struggle to reproduce the issue outside of GitHub Actions.

 [1]: https://github.com/Witiko/lyluatex-github-actions-example
 [2]: https://github.com/Witiko/lyluatex-github-actions-example/actions/runs/3238499683/jobs/5306793830#step:5:72

**Comment by jperon** [comment]
A bit short on time now, and I don’t master github actions well. I should be able to look at this within next month.

**Comment by Witiko** [comment]
The fatal error seems related to the conversion from ESP to PDF, which is not even done by lyluatex, correct? It should be done by Hagen's conversion script when we feed an EPS image to the `\pdfximage` primitive of pdfTeX.

**Comment by jperon** [comment]
I really don’t understand what’s wrong with this. I’ve tried to compile the example within a local `texlive/texlive` controller, and it runs like a charm. @Witiko if you know github actions well, would you have a mean to get a remote shell on it, in order to debug more easily ?

**Comment by jperon** [comment]
I could get my hands on it thanks to https://gist.github.com/lava/62a6697abcaf6e5709939ae29e7bd4be.

The problem originates from the `lilypond` command (launched by `lyluatex`), which returns:

```
warning: g_spawn_sync failed (0): gs: Failed to close file descriptor for child process (Operation not permitted)
```

At first glance, it seems the problem comes from restrictions in the containers spawned by Github. @Witiko  Would you mind trying to create a MWE using only `lilypond` (without LuaLaTeX), to see wether the issue arises ? If so, this bug would have to be signaled upstream.

**Comment by Witiko** [comment]
@jperon Are you certain that the issue is with lilypond? The output seems to suggest that the issue might be with the `gs` command that we also execute in `bbox_parse()` and in `Score:optimize_pdf()`.

**Comment by jperon** [comment]
In the MWE, `optimize-pdf` is not set. In any case, I did get this error by manually launching `lilypond tmp-ly/TMPDOC.ly…`.

**Comment by Witiko** [comment]
Thanks, I will see if I can get to try this sometime this week.

**Comment by Witiko** [comment]
@jperon I added complilation with Lilypond to [witiko/lyluatex-github-actions-example@03bdbf3][1]. As you said in https://github.com/jperon/lyluatex/issues/295#issuecomment-1297463345, [compilation with Lilypond is also failing on GitHub Actions][2]. Therefore, this seems to be an upstream issue.

 [1]: https://github.com/Witiko/lyluatex-github-actions-example/commit/03bdbf3
 [2]: https://github.com/Witiko/lyluatex-github-actions-example/actions/runs/3410133867/jobs/5672721934

**Comment by jperon** [comment]
> Before reporting the issue upstream, I would remove the Lyluatex code and try if the issue persists without the `texlive/texlive:latest` Docker image, so that our MWE is truly minimal.

Good point; if it works with default Github actions, I think it would still be worth reporting upstream, but narrowing the subject to "LilyPond fails to compile documents in GitHub Actions within default texlive image", mentionning especially those lines:

```
warning: g_spawn_sync failed (0): gs: Failed to close file descriptor for child process (Operation not permitted)
fatal error: cannot rename `document-tmp-7187241.502287.pdf' to `document.pdf'
```

**Comment by Witiko** [comment]
I reported the issue [upstream][1].

 [1]: https://gitlab.com/lilypond/lilypond/-/issues/6460

**Comment by Witiko** [comment]
[At the Lilypond GitLab repository][1], I was told to go to [the lilypond-user mailing list][2], which [I did][3].

 [1]: https://gitlab.com/lilypond/lilypond/-/issues/6460
 [2]: https://lists.gnu.org/mailman/listinfo/lilypond-user
 [3]: https://lists.gnu.org/archive/html/lilypond-user/2022-11/msg00062.html
