### ISSUE TITLE
Handling LilyPond compilation failures

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#30]
When a LilyPond compilation fails a Lua stack trace occurs in `write_tex` because it tries to read non-existent files.

This should be handled by at least suppressing the error. Of course the user should *somehow* be notified. In `musicexamples` missing files don't cause an error but an information box is printed instead. I think something similar to that would be a good idea.

**Comment by uliska** [comment]
> I prefer that an error be raised when a non-existent file is trying to be read. 

OK, *I* prefer not interrupting the compilation - so this clearly speaks for making *both* behaviours possible ;-)

> Whether the error is a lua stack trace or a more readable package error doesn't bother me much.

It definitely should be more readable, as that stack trace is pretty confusing for regular users.

> However, now that I think about it, I can also see the benefit of doing something like what `musicexamples` does for the purpose of creating placeholders in a skeletal document, 

That touches a point I've noticed these days. Every now and then I think about implementing something that `musicexamples` does (or plans to do). However, I think we should try to avoid duplication of concerns as much as possible, but this issue shows that it may be more complex than would be desirable. Basically `lyluatex` should *not* produce that yellow placeholder but do something that can make `musicexamples` do so. BUT: the point in keeping the two packages separate is to enable them to work without the other. So what would `lyluatex` do if `musicexamples` is *not* present?

Actually I think we should *not* think this through from the perspective of this current issue item but keep it in mind for a later discussion about the interaction of the two packages in general. I would like to get more familiar with `lyluatex` first, maybe making some more contributions, and then go through `musicexamples` again, probably updating it significantly (probably quite a lot of the code was still pretty naive ...). Then we should discuss the relation of the two packages more generally.

**Comment by jperon** [comment]
Would you like to implement other things on this issue, or may we close it ?

**Comment by uliska** [comment]
Ich will think about IT, I Had one Mode Idea.

**Comment by uliska** [comment]
Actually it's not necessary to keep this one open.
@rpspringuel wants an error to occur (which is the default behaviour), and alternatively a box is printed (which is what I would usually want). 

If anybody ever wants some other behaviour they can open a new issue.
