### ISSUE TITLE
Includepaths no longer working

### ISSUE THREAD

**Issue by rpspringuel** [jperon/lyluatex#304]
I'm working on upgrading a project to use Lilypond 2.24 instead of 2.22 and TeXLive 2022 instead of 2021 and have run into some problems with the includepath option.  Attached is a test document which worked just fine before I started the upgrade process, but now it can't seem to find files which are located relative to the includepath rather than the document.  In the case of the test document, Hymn.ly works fine, but OurFather.ly doesn't (but will, if you give the path relative to the Main.tex location rather than relative to the includepath location).  Any ideas what might be going on here?

Version information is as follows:
LyLuaTeX: 1.1.2
LuaTex:  Version 1.15.0 (TeX Live 2022)
OS: macOS 12.6.3 
Lilypond: 2.24.1 (running Guile 2.2)

[Test_Lily_include.zip](https://github.com/jperon/lyluatex/files/10852092/Test_Lily_include.zip)

**Comment by jperon** [comment]
I’m SO sorry for this stupid error I let enter the code… May you please check it’s fixed in #305 (fix-304 branch)?

**Comment by rpspringuel** [comment]
Yes, it works.

**Comment by jperon** [comment]
Thank you!
