### ISSUE TITLE
Set fonts in LilyPond to the same as in LaTeX

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#32]
It would be nice if it was the default that the fonts in use in the LaTeX document (default fonts, the currently active ones?) are also used in LilyPond.

**Comment by uliska** [comment]
http://lists.gnu.org/archive/html/lilypond-user/2018-01/msg00321.html

It seems it's not that easy. The problem is to get the font *family* name out of Lua.
See also https://tex.stackexchange.com/questions/410992/how-can-i-retrieve-the-current-roman-sans-and-mono-fonts-in-luatex

**Comment by rpspringuel** [comment]
The luatex list is luatex@tug.org.  You can join here: https://www.tug.org/mailman/listinfo/luatex

**Comment by uliska** [comment]
I have achieved a first step: determining the *current* font family. The commit referenced above simply applies this current text font to all three fonts in LilyPond, which of course can't be the end of the line.

One challenge to take is to retrieve the three family names for `\rmfamily`, `\sffamily` and `\ttfamily`.

Then there has to be a discussion about the behaviour:

**a)**  
I suggest not to bother making this an option. First I can see little reason why one would *not* want the text fonts to match, and second it is easy to do so anyway: If the LilyPond code defines text fonts this will happen *after* our code and take precedence.

**b)**
What should be the behaviour if the current font is *not* the one specified by `\rmfamily`?

* ignore that fact and still apply the three fonts (so the main font in the score is the roman font?
* apply the *current* font as the roman font (regardless of what it is) but use the defined sans and typewriter fonts as they are specified. This may result in scores to have both main and sans text to be in the same sans font.

**Comment by rpspringuel** [comment]
a) Agreed.

b) Here an option might be in order.  Perhaps defining `\lyluatex@rmfamily` etc. which default to `\rmfamily` etc. (thus using your first suggestion as the default) and then providing an interface that allows the user to redefine these commands to specify which font specs will be passed to LilyPond in each of those positions (allowing a user to change the behavior if they want the second).

**Comment by uliska** [comment]
Note to self: maybe we have to include the font names in the `output` hash too. A score that is used twice in the same document, but with different fonts will currently not be compiled twice.

**Comment by uliska** [comment]
> Note to self:

Implemented in 5e6d67f0
