### ISSUE TITLE
included score is not horizontally centered.

### ISSUE THREAD

**Issue by kureta** [jperon/lyluatex#320]
I have been trying to figure this out for hours but couldn't find a solution. I am using the Beethoven example `ly` file from this repository. This is the result:

![Screenshot from 2024-01-17 18-10-43](https://github.com/jperon/lyluatex/assets/196420/2327db19-fa66-47ce-b02e-4e6f7f608419)

and this is my `tex` file:

```
% set document class
\documentclass[a4paper]{article}

% Sets page size and margins
\usepackage[a4paper]{geometry}

%% Useful packages
\usepackage{float}
\usepackage{lyluatex}

% === DOCUMENT START ===
\begin{document}
% this creates the title page with title, author and date give above

% asterisk after section makes it unnumbered
\section{Introduction}
This is just for testing purposes.

\begin{figure}[htp]
  \lilypondfile[insert=systems, staffsize=9]{ly/beethoven.ly}
  \caption{bla bla}
  \label{tab:foo}
\end{figure}

\end{document}
```

**Comment by leomcf** [comment]
Hi, I haven't used lyluatex in a while, but I remember that this was an issue when I was using it. It was also driving me nuts, at the time. If I remember correctly, you need to **comment out the title information in the lilypond file**. 
I do *love* the idea of Lylualatex though. It's a new package; I'm sure these bugs will be sorted out in time. Kudos to the developer for making it.

**Comment by kureta** [comment]
@leomcf thank you very very much! There is no way I could have been able to find it on my own. Closing the issue now. Thanks again

**Comment by rpspringuel** [comment]
This is a duplicate of #307.

**Comment by leomcf** [comment]
HTH @kureta!

**Comment by kureta** [comment]
@rpspringuel Thanks. I couldn't find it before. I'll subscribe to it now.
