### ISSUE TITLE
Index of scores

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#33]
While storing the scores by their content hash is of course indispensable it effectively renders the tmp_ly directory a black box.

Maybe there should be an index (in addition to the .list file already exported) that allows mapping some reference from the source to the hash.

A suggestion would be to combine that with a label. A key "label" would generate a label after the image and would add an entry to the index

**Comment by jperon** [comment]
> A suggestion would be to combine that with a label. A key "label" would generate a label after the image and would add an entry to the index

I think it would be better to distinguish two things : 

- mapping names to hash, which might be useful for debugging purposes, even without an index;
- table of content or index.

The second point, IMHO, is already managed by ordinary LaTeX commands, and users could wrap them in their own commands; so I'd rather:

- or let users define their own commands;
- or implement this in musicexamples.

**Comment by jperon** [comment]
Do you think the actual behaviour (mapping hash to name in `jobname.list`) is enough, or should we let this open for now ?

**Comment by jperon** [comment]
Closing; feel free to re-open if I forgot something.
