### ISSUE TITLE
Currently supported options from lilypond-book

### ISSUE THREAD

**Issue by rpspringuel** [jperon/lyluatex#37]
If `lyluatex` is to be a drop-in replacement for `lilypond-book`  Then the goal should be to support all the [`lilypond-book` music fragment options](http://lilypond.org/doc/v2.19/Documentation/usage/music-fragment-options).  This list is intended to keep track of what is currently supported and what is not:

- [x] staffsize=_ht_
- [ ] ragged-right
- [ ] noragged-right
- [ ] line-width
- [x] line-width=_size\unit_
- [ ] papersize=string
- [ ] notime
- [ ] fragment
- [x] nofragment
- [ ] indent=_size\unit_
- [ ] noindent
- [ ] quote
- [ ] exampleindent
- [ ] relative
- [ ] relative=_n_

There are also the following options which are specifically designed for LilyPond's documentation and thus of lower priority:

- [ ] verbatim
- [ ] addversion
- [ ] texidoc
- [ ] doctitle
- [ ] nogettext
- [ ] printfilename

**Comment by rpspringuel** [comment]
Based on my reading of the `keycommand` package, it is not possible to support a keyword which is both boolean (given or not given) and general (given with a value).  That is `line-width` without a value cannot be supported along side `line-width=size\unit` (similar for `relative` and `relative=n`).  I'm not so sure about other ways of defining keyword commands (such as `keyval` or `pfgkeys`).

**Comment by uliska** [comment]
@rpspringuel have you ever looked into the (rather new) Github feature of "projects"? Maybe `lilypond-book` compatibility would be a good candidate for that. The checklist would then become a backlog, with the advantage that each item could become an issue (with assignee, comments etc.).

**Comment by rpspringuel** [comment]
No, I haven't.  I'll look into converting this into one of those now, as it seems like as good a time as any to familiarize myself with the new feature.

**Comment by rpspringuel** [comment]
Now [Project #1](https://github.com/jperon/lyluatex/projects/1)

**Comment by rpspringuel** [comment]
> So for now I suggest that in order to comment on notes we edit them but clearly mark the edit as comments.

The one problem I see here, is that the cards are limited in size.  Any issue that really starts to generate discussion will quickly run out of space and require conversion to an Issue anyway in order to continue the discussion.
