### ISSUE TITLE
Contrôle des modifications

### ISSUE THREAD

**Issue by philmassart** [jperon/lyluatex#4]
Votre package me semble très intéressant, je vais le tester sur des documents plus importants pour voir comment se passe l'inclusion de bibliographie, index etc. Mais déjà bravo pour votre travail.

Une question: il me semble que les extraits de lilypond sont compilés à chaque fois, ce qui peut être fastidieux pour les gros fichiers. Pensez-vous y intégrer un système de contrôle des modifications pour ne compiler que les extraits modifiés depuis la dernière compilation?

**Comment by jperon** [comment]
En effet, les extraits inclus dans le corps du document sont compilés à chaque fois (contrairement aux partitions externes, qui ne sont recompilées qu'en cas de changement dans la partition ou dans les dimensions de la page). J'ai vu depuis un moyen qui me permettrait de faire autrement, mais il faut que je trouve comment faire un *hash* du contenu du fichier en lua.

**Comment by jperon** [comment]
Pourriez-vous, s'il vous plaît, tester la dernière modification ? Elle devrait résoudre le problème.

**Comment by philmassart** [comment]
Parfait :-) Merci beaucoup!
