### ISSUE TITLE
Wish: inline scores

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#45]
I'd like to implement a third mode beside fullpage and fragment: inline. Basically this should produce an image and include it like a character - actually a `lilyglyphs` command but "live". Differences from fragments include

* other boilerplate
* options to hide/show stafflines, clef, key (default: omitted)
* no handling of indentation
* maybe a different staffsize heuristic

**Comment by jperon** [comment]
I think it could be implemented as a wrapper macro around `\lily`. Just an idea.

**Comment by uliska** [comment]
Or as a (local-only) option:

\lily[inline=true,hide={staff,key}]{ c'8  d' c' d' }

Well, the configuration should be done in the usual three ways.

**Comment by uliska** [comment]
> Well, the configuration should be done in the usual three ways.

Indeed, it should (by now) be `insert=inline`, along with the `notime`, `nostaff` etc. options.

---

From the lilypond-book description of `verbatim`:

> This option does not work well with \lilypond{} if it is part of a paragraph.

Do I read this correctly that (at least) `\lilypond` does *not* wrap the score in a paragraph but will just print the image wherever the macro is placed?
If so, do we have to copy *that* behaviour too? Actually I would prefer a consistent behaviour of paragraph wrapping as we have it now and manually having to set the `inline` mode.

A compromise could be to make `\lilypond` use `inline` as default (when nothing is set) and the others `systems`. Although it is a little bit inconsistent and could therefore be confusing.

Opinions?

**Comment by jperon** [comment]
> A compromise could be to make `\lilypond` use `inline` as default (when nothing is set) and the others systems.

I think it's the best solution, as IMHO using `lilypond` for more than a few notes would be bad practice.
