### ISSUE TITLE
Fullpage option also for fragments

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#46]
There is no reason to prohibit fragments to be fullpage. Think of auto-generated exercises or patterns that can very well be coded inline.

I think with the new option handling this should be much simpler, and it will also enable the removal of code redundancy between `lilypond_file()` and `lilypond_fragment()`.

`fullpage` will of course be changed from a function argument to `get_local_option()` too.

**Comment by jperon** [comment]
Closing this one, fixed in #48.
