### ISSUE TITLE
Wrong output with \includely

### ISSUE THREAD

**Issue by VictorCisneros** [jperon/lyluatex#5]
If some small music is correctly generated by the **ly** environment, and later is replaced by another one, LuaLaTeX will fail to render the second one, printing always the first. Deleting the auxiliary files seems to be the only way to get the new snippet to the pdf.

Maybe a *force* option could be added to help with this issues?

**Comment by jperon** [comment]
I've quickly tried to reproduce it, but I couldn't : when I modify the content of the `ly` environment, the output is correctly changed. Are you looking at the final result, or at the temporary files within `tmp_ly` ? If you're in the second case, the temporary files coming from a `ly` environment are never changed, as their name is computed from the content : if the content changes, a new temporary file is created (and the old one isn't removed, unless you remove it yourself).

Could you please send me an example to cataclop@hotmail.com ?

**Comment by VictorCisneros** [comment]
I'm not able to reproduce it anymore, I guess it was my mistake... I'll let you know if it shows up again. Sorry for the false alarm.

**Comment by VictorCisneros** [comment]
So I stumbled it again, but I was wrong about the ly environment. It is with `\includely` command that after being correctly rendered, if I change my .ly file, and then recompile, the change will not be noticed. Also if the compiler fails, and the error is corrected, it'll still complain about it and wont finish the process. Only manually deleting all auxiliary files seems to solve the problem.

I'm compiling with `latexmk -cd -e $pdflatex = 'lualatex -shell-escape -interaction=nonstopmode -synctex=1 %S %O' -f -pdf`. Is this a problem with your package or with my compiler?

**Comment by jperon** [comment]
`latexmk -cd -e $pdflatex = 'lualatex -shell-escape -interaction=nonstopmode -synctex=1 %S %O' -f -pdf` throws an error on my system, but I tried the equivalent 
`latexmk -cd -pdflatex="lualatex -shell-escape -interaction=nonstopmode -synctex=1 %S %O" -f -pdf`

It doesn't notice the change indeed, which comes (I guess) from the fact `\includely` isn't an `\include`  statement. You could add the `-g` switch to your command, which will force compilation ; I really don't know how that could be corrected from lyluatex side.
