### ISSUE TITLE
Better handle of options

### ISSUE THREAD

**Issue by jperon** [jperon/lyluatex#55]
Till now : 
- we define a special command to change every global option within the doc ;
- we add special parts to the name of temporary files in `hash_output_filename` ;
- we define options in three places : at the beginning of `lyluatex.sty`, and when defining `ly` and `lily`.

This should be refactored : 
- we should have only one command, say `\lysetoption{OPTION}`, that would change each parameter ;
- we should take all options in account in `hash_output_filename`, and include them in the hash instead of defining *very* long filenames (that may only get longer while adding options) ;
- we should have a lua function (or another way) to define `ly` and `lily`'s options.

That way, every option could be defined : 
- either globally as a package option ;
- or globally within the document ;
- or locally as a command option.

While it wouldn't necessarily mean something for every option, nothing prohibits to make it possible. Perhaps we would be amazed by users' ingeniousness…

I'll work on this as from wednesday.

**Comment by uliska** [comment]
This totally makes sense. I have just one additional wish: while you're at that could you implement some sore ot (fake) type check in that hypothetical `\lysetoption{}` command? Since we still have strings as input it would be good to check if a given option matches the expected type and/or set of expected values.

**Comment by uliska** [comment]
I *did* start some code clean-up on the https://github.com/jperon/lyluatex/tree/program-flow branch which is intended as a preparation of your options work. It should be mergeable before you start, but if I shouldn't have opened a pull request by the time you want to work on it please check what's going on on that branch.
