### ISSUE TITLE
REQ: Lilypond working directory

### ISSUE THREAD

**Issue by VictorCisneros** [jperon/lyluatex#6]
Is there a way to set a working directory for lilypond? I'm using a complex structure for my project, and when I compile my files only with lilypond, all `\include`d files are found correctly; but when compiling with LuaLaTeX they are no longer found. This is because the relative path changes from one file to the other, so it would be nice to add some working directory parameter to lyluatex, so lilypond can find her files without having to symlink them.

**Comment by rpspringuel** [comment]
You might try adding `#(ly:set-option 'relative-includes #t)` to the head of your Lilypond files.  This option will make it so that any include statements in the file are taken to be relative to the file's location, rather than the working directory from which lilypond was invoked.

**Comment by VictorCisneros** [comment]
No, I'm trying this right now and the path is always relative to the .tex file. In the process, I stumbled across the bug in the other thread, I'll explain it there.

**Comment by jperon** [comment]
Could you please send me an archive with an elementary project like this ? I'll have a look at this problem tomorrow.

**Comment by VictorCisneros** [comment]
[Here](https://www.dropbox.com/s/w68pw2gd101j2vp/Example.rar?dl=0) you can see an example. In master.pdf you can see the incorrect output, and in music/music_example.pdf the expected output. If you add `#(ly:set-option 'relative-includes #t)` to music_example.ly the output remains the same.

**Comment by jperon** [comment]
I think I've seen the problem : as lyluatex outputs temporary results to `tmp_ly/TREE`, this adds one level to the hierarchy of folders. As a result, `../style/style.ly` is equivalent to `project/tmp_ly/style/style.ly`.

I've corrected that in last commit, may you try it please ?

**Comment by VictorCisneros** [comment]
It seems to work correctly now, thank you very much.

**Comment by jperon** [comment]
I'll leave this open for now, as I think the fix is really a workaround, that doesn't cover all possible cases.

**Comment by jperon** [comment]
The last commit should really solve the problem : the folder of the lilypond score is now included in search path at compile time. Let me know wether you encounter bugs ; if not, I'll close this issue.

**Comment by VictorCisneros** [comment]
I've tested it on my project today without any problem. Thank you so much for this. Regards.
