### ISSUE TITLE
lilypond-book command/env names

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#60]
Maybe this is a stupid question, but why do we have to use our "private" command/environment names (`\lily`, `ly`, `\inlcudely`) instead of directly using those from `lilypond-book` (`\lilypond`, `lilypond`, `\lilypondfile`)?

Wouldn't it be much better to simply reuse these names from `lilypond-book`? I find them very telling, and I don't see the reason to deviate from them and create an additional compatibility layer.

If compatibility with existing documents is the reason, are there really that many already out there in the wild (I mean, even in `test.tex` we use `\lilypondfile`)?  And if so I would at least suggest to invert the situation, make the `lilypond-book` names the default and create aliases for the others.

**Comment by jperon** [comment]
We cannot directly define a command and an environment with the same name (look at the code at the end of `lyluatex.sty`) ; so in any case, we would have to define them first, then assign the name `lilypond`. The "temporary" names could be internal macros (`ly@something`) ; but as they already exist and could be used in existing documents, I don't think it's necessary to change them.

**Comment by uliska** [comment]
OK, I see. But then I'd say we should basically use the lilypond-book like names exclusively in the documentation.

**Comment by jperon** [comment]
> we should basically use the lilypond-book like names exclusively in the documentation.

I agree for the *user* docs, but I think we should suggest `\lily` and `ly` for package authors.
