### ISSUE TITLE
Add "label" argument

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#62]
Add a `label` argument (which will only make sense as a local option, of course).

* Insert a `\label` after the image
* Prefix the label with a configurable prefix
* Make sure this works well with `musicexamples`
* If a label is defined, use it for the FILELIST output

**Comment by jperon** [comment]
If you want, I could implement it: as it's quite simple, just viewing the diff woud help you to understand the logic behind the new flow.

**Comment by uliska** [comment]
OK, that would be nice. I'll soon start getting into actual work again and deal with the horizontal alignment/protrusion questions. In the meantime I've started work on sections in the manual.

**Comment by jperon** [comment]
Fixed by cc2ea9b.
