### ISSUE TITLE
line-width option

### ISSUE THREAD

**Issue by jperon** [jperon/lyluatex#67]
line-width=size\unit

Set line width to `size`, using `unit` as units. `unit` is one of the following strings: `cm`, `mm`,` in`, or `pt`. This option affects LilyPond output (this is, the staff length of the music snippet), not the text layout.

If used without an argument, set line width to a default value (as computed with a heuristic algorithm).

If no line-width option is given, lilypond-book tries to guess a default for lilypond environments which don’t use the `ragged-right` option.

We currently support the `line-width=size\unit` option, but not the `line-width` option.  As best I can tell, the `keycommand` package cannot support a key which is both boolean (given or not given) and general (given with a value).  I'm not sure if other keyword packages (such as `keyval` or `pfgkeys`) provide the needed support.

**Comment by jperon** [comment]
I think we can consider this point as done:
- in `lilypond-book`, this isn't a global option, but an option to each command/environment;
- in `lyluatex`:
    - it isn't possible to set a single `line-width` as package option, as it raises an error from `xkeyval`;
    - it *is* possible to set it as a command option, that gets ignored; but as it is the default behaviour, it gives the expected result.

**Comment by uliska** [comment]
What happens when the line width is globally set to some value and `[line-width]` is used as a local option?

**Comment by jperon** [comment]
It will be auto-calculated. That's the expected behaviour as defined [here](http://lilypond.org/doc/v2.18/Documentation/usage/music-fragment-options).

**Comment by uliska** [comment]
I know this is the wanted behaviour. I couldn't test if it would actually do that (as in that case the option isn't actually set to '' but some other value).

**Comment by jperon** [comment]
In fact, it *is* set to '': the package `keycommand` makes no difference between `line-width=` and `line-width`.

**Comment by uliska** [comment]
I see.
So I agree this is done
