### ISSUE TITLE
"label" as local option?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#69]
I'm somewhat confused, but I have the impression the `label` option is not recognized as a local option. It works as package option and with `\lysetoption` but not as a local option.

I can't see any reason in the code, though.

**Comment by jperon** [comment]
I don't see that here. For example, if I compile (twice) [test.tex](https://github.com/jperon/lyluatex/blob/master/test.tex), I have the good page number on the first page (just after the first score).

**Comment by uliska** [comment]
Sorry, I enclosed the label in quotes ...
