### ISSUE TITLE
Compilation fails with "Attempt to call global 'direct_ly' (a nil value)"

### ISSUE THREAD

**Issue by alex-ball** [jperon/lyluatex#80]
I cannot get the package to work at all on my system.

  - Compiler: LuaTeX, Version 1.0.4 (TeX Live 2017)
  - OS: Linux (Ubuntu 16.04)

MWE:

```latex
\documentclass{article}
\usepackage{lyluatex}
\begin{document}
\begin{ly}
\relative c { a b c d }
\end{ly}
\end{document}
```

In interactive mode, compilation drops out to a lua prompt after the following line:

```latex
(/path/to/texmf-dist/tex/latex/pdfpages/ppluatex.def)
```

Error message in batch mode:

```latex
[\directlua]:1: attempt to call global 'direct_ly' (a nil value)
stack traceback:
	[\directlua]:1: in main chunk.
\env@compilerly@process ...g {\localstaffsize } )}
                                                  \env@ignore 
l.6 \end{ly}
          
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.
```

**Comment by uliska** [comment]
Please

* tell us which version of the package you use (TeXLive, CTAN, Github)
* give us the complete command line

**Comment by jperon** [comment]
I think it's a weird bug I've already observed. Could you please try following commands:
```
sudo ln -s /usr/share/texlive/texmf-dist/scripts/lyluatex/lyluatex.lua /usr/share/texmf/tex/latex/lyluatex/lyluatex.lua
sudo mktexlsr
```
then try again ?

**Comment by alex-ball** [comment]
@jperon:
Yes, that worked. Thanks for that.

@uliska:
For completeness, I'm using the TeXLive version (up to date with tlmgr), and invoke compilation as per the documentation:
```bash
lualatex -shell-escape test.tex
```

**Comment by jperon** [comment]
I leave this open, as I'll have to report it to TeXLive.

**Comment by jperon** [comment]
After testing more on my machine, it seems this bug has disappeared with last changes; I guess this could be related to namespace-issues.
So I close it now; it will be solved upstream when we've sent the new version to CTAN.

**Comment by jperon** [comment]
@alex-ball When it's been updated on TeXLive and you update your own distribution, you shouldn't forget to revert previous commands (just to keep your installation clean):

```
sudo rm /usr/share/texmf/tex/latex/lyluatex/lyluatex.lua
sudo mktexlsr
```
