### ISSUE TITLE
Question: tmpdir relative to what?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#88]
Currently the temp dir is created relative to the current dir and not relative to the .tex file. Also there is no notion of absolute paths, the option value will simply be used relative to the current dir.

1. Shouldn't the temp dir be considered relative to the *document*?
2. Shouldn't we support relative-to-home and absolute paths?
3. Shouldn't there be some more checks for, say, trailing slashes?

**Comment by jperon** [comment]
That's quite a dangerous area, as we would have to deal with TeXLive's `openin` and `openout`. It's so complicated (for me at least) that I'd better document that the main document is to be compiled from its own directory.

**Comment by uliska** [comment]
OK, I'll do so. We can change things at any later point, or not ...
