### ISSUE TITLE
Translate README.md to English

### ISSUE THREAD

**Issue by meisterluk** [jperon/lyluatex#97]
Personally, I can understand French texts, but this does not apply to everyone. The general consensus in TeX/IT or on github is that English is used as a documentation language.

Therefore, I create this issue to track the translation of `README.md` to English.

**Comment by jperon** [comment]
What about [this](https://github.com/jperon/lyluatex/blob/master/README.en.md) ?

**Comment by meisterluk** [comment]
Oh my, I am so sorry. I should have taken a closer look. Thank you @jperon, sorry for the noise.

**Comment by jperon** [comment]
No problem, you're welcome !

**Comment by fedelibre** [comment]
@jperon IMO README.md should be renamed to README.fr.md and README.en.md should be renamed to README.md, so english will be the default language in "homepage". As a matter of fact, english is the common language...
